---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# arboretum

<!-- badges: start -->
<!-- badges: end -->

Plot customised phylogentic trees.

## Installation

You can install the development version of arboretum from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("dkidney/arboretum")
```

## Examples

Plot the default tree.

```{r fig.asp = 0.6, fig.width = 10}
library(arboretum)
tree() # default settings
```

Create customised trees by selecting a specific taxon and/or collapsing specific taxa.

```{r fig.asp = 0.6, fig.width = 10}
tree(taxon='amniota', 
	 collapse=c('archosauromorpha', 'therapsida', 'lepidosauromorpha'))
```

```{r fig.asp = 0.6, fig.width = 10}
tree(taxon='archosauromorpha', 
	 collapse=c('dinosauria', 'pterosauria', 'pseudosuchia', 'sauropterygia'))
```


```{r fig.asp = 0.6, fig.width = 10}
tree('dinosauria', 
	 collapse = c('sauropoda', 'ornithopoda', 'theropoda', 'ankylosauria', 'ceratopsia'))
```

```{r fig.asp = 0.6, fig.width = 10}
tree(taxon='tetanurae', collapse=c('avialae'))
```
