suppressPackageStartupMessages({
	library(magrittr)
	library(tidyverse)
})

df = tribble(
	~taxon, ~from, ~to, ~children, ~notes,
	"abelisauridae", -143, -66, "carnotaurus", "'Abel's lizards'",
	"acanthostega", -365, -365, NA, NA,
	"aepyornithiformes", -2.58, -0.001, NA, " elephant birds, incl Aepyornis",
	"aetosauria", -231.4, -201.4, "aetosaurus, desmatosuchus", NA,
	"aetosaurus*", -227.3, -205.7, NA, NA,
	"afrotheria", -65, -65, "proboscidea, sirenia", NA,
	"alamosaurus", -70, -66, NA, NA,
	"albertosaurus", -71, -68, NA, NA,
	"alioramus", -70, -70, NA, NA,
	"alligator", -37.2, 0, NA, NA,
	"alligatoroidea", -83.6, 0, "alligator, caiman, deinosuchus", NA,
	"allosauridae", -179.17, -179.17, "allosaurus", NA,
	"allosaurus", -155, -143.1, NA, NA,
	"alvarezsauridae", -97, -66, "alvarezsaurus", NA,
	# "alvarezsauroidea", -160, -66, NA, NA,
	"alvarezsaurus", -86, -83, NA, NA,
	"ambulocetus", -48, -47, NA, NA,
	"amniota", -323, -323, "sauropsida, synapsida", NA,
	"andrewsarchus", -47.8, -37.71, NA, NA,
	"anhangueridae", -140, -92.5, NA, NA,
	"ankylosauria", -167, -167, "ankylosauridae, nodosauridae", NA,
	"ankylosauridae", -122, -66, "ankylosaurus, euoplocephalus", NA,
	"ankylosaurus", -68, -66, NA, NA,
	"anura", -200, 0, NA, "frogs and toads",
	"apatosaurus", -152, -151, NA, NA,
	"apterygidae", -23, 0, NA, "kiwis",
	"araeoscelidia", -302, -275.6, NA, NA,
	"archaeopteryx", -150.8, -148.5, NA, "'old-wing', Southern Germany",
	"archegosauridae*", -300, -252, "archegosaurus, prionosuchus", NA,
	"archegosaurus", -299, -253, NA, NA,
	"archelosauria", -260, -260, "archosauromorpha, pantestudines", NA,
	"archosauria", -248, -248, "avemetatarsalia, pseudosuchia", NA,
	"archosauriformes", -252, 0, "archosauria, erythrosuchus, euparkeria, vancleavea", NA,
	"archosauromorpha", -260, -260, "archosauriformes, ichthyosauromorpha, rhynchosauria, sauropterygia, thalattosauria", NA,
	"argentinosaurus", -96.2, -92.19, NA, NA,
	"artiodactyla*", -60, -60, "andrewsarchus, cetacea, entelodontidae", NA,
	"atrociraptor", -72.2, -71.5, NA, NA,
	"attenborosaurus", -196.5, -189.6, NA, NA,
	"australovenator", -95, -95, NA, NA,
	"avemetatarsalia", -247, -247, "dinosauromorpha, pterosauria", NA,
	"aves*", -75, -75, "neognathae, palaeognathae", NA,
	"avialae", -150.8, -150.8, "archaeopteryx, enantiornithes, euornithes", NA,
	"azhdarchidae", -92, -66, NA, "includes Quetzalcoatlus",
	"barinasuchus", -42.2, -11.8, NA, NA,
	"barosaurus", -152, -150, NA, NA,
	"baryonyx", -130, -125, NA, "'heavy claw', UK",
	"basilosauridae", -43, -33.9, "basilosaurus, dorudon", NA,
	"basilosaurus", -41.3, -33.9, NA, NA,
	"batrachotomus", -242, -237, NA, NA,
	# "biarmosuchia", -272.5, -252, NA, NA,
	"borhyaena", -21, -15.5, NA, NA,
	"borhyaenidae*", -63, -5.333, "borhyaena, lycopsis", NA,
	"brachiosauridae", -160, -100, "brachiosaurus, giraffatitan", NA,
	"brachiosaurus", -154, -150, NA, NA,
	"brontosaurus", -156.3, -146.8, NA, NA,
	"brontotheriidae", -56, -34, NA, NA,
	"caiman", -16, 0, NA, NA,
	"camarasaurus", -155, -143.1, NA, NA,
	"camptosaurus", -156.3, -146.8, NA, NA,
	"canidae", -37.8, 0, NA, NA,
	"carcharodontosauridae", -154, -154, "carcharodontosaurus, concavenator, giganotosaurus, neovenator, tyrannotitan", NA,
	"carcharodontosaurus", -100, -94, NA, "'jagged toothed lizard', Northwest Africa",
	"carnivora", -51.88, 0, "canidae, felidae, ursidae", NA,
	"carnosauria*", -180, -180, "allosauridae, carcharodontosauridae, metriacanthosauridae", NA,
	"carnotaurus", -72, -69, NA, NA,
	"casuariiformes", -23, 0, NA, "cassowarys and emus",
	"centrosaurus", -76.5, -75.5, NA, NA,
	"ceratopsia", -161, -66, "ceratopsidae, protoceratops, psittacosaurus", NA,
	"ceratopsidae*", -90, -66, "centrosaurus, chasmosaurus, diabloceratops, pachyrhinosaurus, styracosaurus, triceratops", NA,
	"ceratosauria", -199.3, -199.3, "abelisauridae, ceratosaurus, noasauridae", NA,
	"ceratosaurus", -153, -148, NA, "'horn lizard', USA",
	"cetacea", -56, -56, "ambulocetus, basilosauridae, mysticeti, odontoceti, pakicetus, rodhocetus", NA,
	"cetiosauridae", -178, -161, "cetiosaurus", NA,
	"cetiosaurus", -170, -164.7, NA, NA,
	"chalicotheriidae", -48.6, -1.806, NA, NA,
	# "chalicotherioidea", -48.6, -0.005, NA, NA,
	"chamaeleonidae", -26, 0, NA, NA,
	"chasmosaurus", -77, -76, NA, NA,
	"chiroptera", -56, 0, NA, NA,
	"cingulata", -58.7, 0, "glyptodontinae", "armadillos",
	"coelophysis", -215, -208.5, NA, NA,
	"coelophysoidea", -227, -183, "coelophysis, dilophosaurus", NA,
	"coelurosauria*", -170, -170, "compsognathidae, maniraptora, ornitholestes, ornithomimosauria, tyrannosauroidea", NA,
	"compsognathidae", -151.5, -108, "compsognathus, sinosauropteryx", NA,
	"compsognathus", -150.8, -145, NA, NA,
	"concavenator", -125, -125, NA, NA,
	"corythosaurus", -77, -75.7, NA, NA,
	"crocodilia", -100, -100, "alligatoroidea, crocodyloidea, gavialoidea", NA,
	"crocodylidae", -46, 0, "crocodylus", NA,
	"crocodyliformes", -225, -225, "crocodilia, notosuchia, pholidosauridae", NA,
	"crocodyloidea*", -70, 0, "crocodylidae", NA,
	"crocodylomorpha", -235, -235, "crocodyliformes, sphenosuchia, thalattosuchia", NA,
	"crocodylus", -25, 0, NA, NA,
	"cryptoclididae", -170, -130, "cryptoclidus, kimmerosaurus", NA,
	"cryptoclidus", -166, -160, NA, NA,
	"ctenosauriscidae", -247.5, -237, NA, "all species had large 'sails' on their backs",
	"cynodontia", -260, -260, "cynognathus, mammaliamorpha", NA,
	"cynognathus", -247, -237, NA, NA,
	"dacentrurus", -154, -140, NA, NA,
	"daspletosaurus", -78, -74.4, NA, NA,
	"deinocheiridae", -115, -69, "deinocheirus", NA,
	"deinocheirus", -70, -70, NA, NA,
	"deinonychosauria", -167, -167, "dromaeosauridae, troodontidae", NA,
	"deinonychus", -115, -108, NA, NA,
	"deinosuchus", -82, -73, NA, NA,
	"deinotheriidae", -28, -1, "deinotherium", NA,
	"deinotherium*", -13, -1, NA, NA,
	"desmatosuchus", -228, -210, NA, NA,
	"diabloceratops", -81.4, -81, NA, NA,
	"diadectes", -290, -272, NA, "'crosswise-biter' one of the first herbivorous tetrapods, one of the first fully terrestrial vertebrates to attain large size",
	"diadectidae", -305, -256, "diadectes, diasparactus", NA,
	"diapsida", -302, -302, "sauria", NA,
	"diasparactus", -296.4, -295, NA, NA,
	"dicynodontia", -268, -201.4, "lisowicia, lystrosaurus, placerias", "'two dog tooth'",
	"didelphodon", -73, -66, NA, NA,
	"dilong", -130, -122.5, NA, NA,
	"dilophosaurus", -195.2, -183.7, NA, "two-crested lizard",
	"dimetrodon", -295, -270, NA, NA,
	"dimorphodontidae", -208, -182, NA, NA,
	"dinocephalia", -279, -260, "moschops", "'terrible head'",
	"dinornithiformes", -17, -6e-04, NA, "moas, incl Dinornis",
	"dinosauria*", -240, -240, "ornithischia, saurischia", NA,
	"dinosauromorpha", -247, -247, "dinosauria", NA,
	"diplocaulus", -306, -255, NA, NA,
	"diplodocidae", -170, -136.4, "apatosaurus, barosaurus, brontosaurus, diplodocus", NA,
	"diplodocus", -154, -152, NA, NA,
	"diprotodon", -1.77, -0.04, NA, NA,
	# "diprotodontia", -28, 0, NA, NA,
	"diprotodontidae", -28.4, -0.04, "diprotodon", "giant wombats",
	"dorudon", -41.03, -33.9, NA, NA,
	"dreadnoughtus", -76, -70, NA, NA,
	"dromaeosauridae", -145, -145, "eudromaeosauria, microraptor", NA,
	"dromaeosaurus", -80, -69.1, NA, NA,
	"dryosauridae", -164, -115, "dryosaurus", NA,
	"dryosaurus", -155, -145, NA, NA,
	"edaphosauridae", -307, -272, "edaphosaurus", NA,
	"edaphosaurus", -303.4, -272.5, NA, NA,
	"edmontonia", -76.5, -69, NA, NA,
	"edmontosaurus", -73, -66, NA, NA,
	"elasmosauridae", -130, -66, "elasmosaurus", NA,
	"elasmosaurus", -80.64, -77, NA, NA,
	"elephantidae", -10, 0, "elephas, loxodonta, mammuthus, palaeoloxodon", NA,
	"elephas", -5, 0, NA, "Asian elephants",
	"elginerpeton", -375, -375, NA, NA,
	"enantiornithes", -136, -66, NA, "'opposite birds'",
	"entelodontidae", -37.2, -15.97, NA, NA,
	"eodromaeus", -231.4, -229, NA, "'dawn runner', Argentina",
	"eoraptor", -231, -228, NA, "maybe a sauropodomorph?",
	"eotyrannus", -130, -130, NA, NA,
	"epidexipteryx", -164, -164, NA, NA,
	"equidae", -55.8, 0, NA, NA,
	"eryops", -299, -273, NA, NA,
	"erythrosuchus", -249, -244, NA, NA,
	"euarchontoglires", -66, -66, "lagomorpha, primates, rodentia", NA,
	"eudromaeosauria", -143, -66, "atrociraptor, deinonychus, dromaeosaurus, pyroraptor, utahraptor, velociraptor", NA,
	"euhelopodidae", -145, -88, NA, NA,
	"euoplocephalus", -76.4, -75.6, NA, NA,
	"euornithes", -130.7, -130.7, "aves, hesperornis, ichthyornis", NA,
	"euparkeria", -247, -247, NA, NA,
	"eureptilia", -311, -311, "araeoscelidia, diapsida", NA,
	"europelta", -113, -113, NA, NA,
	"eutheria", -125, -125, "placentalia", NA,
	"felidae", -30.8, 0, "smilodon", NA,
	"fukuiraptor", -125, -115, NA, NA,
	"gallimimus", -70, -70, NA, NA,
	"galloanserae", -72, 0, NA, "maastrichtian",
	"gavialidae", -38, 0, "gavialis", NA,
	"gavialis", -20, 0, NA, NA,
	"gavialoidea*", -70, 0, "gavialidae", NA,
	"gekkota", -100, 0, NA, NA,
	"giganotosaurus", -99.6, -95, NA, "'giant southern lizard', Argentina",
	"giraffatitan", -150, -145, NA, NA,
	"glyptodon", -3.2, -0.011, NA, NA,
	"glyptodontinae", -38, -0.011, "glyptodon", NA,
	"gomphotheriidae", -28, -0.01, "gomphotherium", NA,
	"gomphotherium", -16, -5, NA, NA,
	"gorgonops", -260, -254, NA, NA,
	"gorgonopsia", -270, -252, "gorgonops, lycaenops", NA,
	"gorgosaurus", -76.5, -75, NA, NA,
	"gracilisuchidae", -247.2, -234, NA, NA,
	"gymnophiona", -223, 0, NA, "caecilian",
	"hadrosauridae*", -90, -66, "corythosaurus, edmontosaurus, hadrosaurus, lambeosaurus, maiasaura, parasaurolophus, shantungosaurus", NA,
	"hadrosaurus", -83.6, -77.9, NA, NA,
	"herrerasauridae", -233.23, -233.23, "herrerasaurus, staurikosaurus", NA,
	"herrerasaurus", -231.4, -228.91, NA, NA,
	"hesperornis", -83.6, -72, NA, NA,
	"heterodontosaurus", -200, -190, NA, NA,
	"hyaenodontidae", -55.2, -16.9, NA, NA,
	"hypsilophodon", -130, -125, NA, NA,
	"ichthyornis", -95, -83.5, NA, NA,
	"ichthyosauromorpha", -251.3, -90, NA, NA,
	"ichthyostega", -365, -360, NA, NA,
	# "ichthyostegalia", -368, -329, NA, NA,
	"iguanodon", -126, -122, NA, NA,
	"irritator", -113, -110, NA, NA,
	"kentrosaurus", -152, -152, NA, NA,
	"kimmerosaurus", -152, -150, NA, NA,
	"kronosaurus", -125, -99.6, NA, NA,
	"lagomorpha", -59, 0, NA, NA,
	"lambeosaurus", -76, -75, NA, NA,
	"laurasiatheria", -65, -65, "artiodactyla, carnivora, chiroptera, hyaenodontidae, perissodactyla", NA,
	"lepidosauromorpha", -252, -252, "rhynchocephalia, squamata", NA,
	"lepospondyli", -339, -251.902, "diplocaulus", NA,
	"leptocleididae", -145, -100.5, "leptocleidus", NA,
	"leptocleidus", -135, -125, NA, NA,
	"leptosuchus", -237, -208.5, NA, NA,
	"liopleurodon", -166, -155, NA, NA,
	"lisowicia", -210, -205, NA, NA,
	"lissamphibia", -250, -250, "anura, gymnophiona, urodela", NA,
	"lotosaurus", -238, -238, NA, NA,
	"loxodonta", -7, 0, NA, "African elephants",
	"lycaenops", -260, -260, NA, NA,
	"lycopsis", -16.3, -9, NA, NA,
	"lystrosaurus", -255, -248, NA, NA,
	"maiasaura", -86.3, -70.6, NA, NA,
	"mamenchisauridae", -184.5, -114, "mamenchisaurus", NA,
	"mamenchisaurus", -161, -114.4, NA, NA,
	"mammalia", -167, -167, "monotremata, multituberculata, theria", NA,
	"mammaliaformes", -227, -227, "mammalia, morganucodonta", NA,
	"mammaliamorpha", -232, -232, "mammaliaformes", NA,
	"mammuthus", -6.2, -0.004, NA, NA,
	"maniraptora*", -167, -167, "alvarezsauridae, oviraptoridae, paraves, therizinosauridae", NA,
	"mantellisaurus", -130, -120, NA, NA,
	"marginocephalia*", -165, -165, "ceratopsia, pachycephalosauria", NA,
	"marsupalia", -66, 0, "diprotodontidae, thylacinidae, thylacoleonidae", NA,
	"massospondylidae", -227, -176, "massospondylus", NA,
	"massospondylus", -200, -183, NA, NA,
	"megalosauridae", -170, -145, "megalosaurus, torvosaurus", NA,
	"megalosauroidea*", -175, -175, "megalosauridae, spinosauridae", NA,
	"megalosaurus", -166, -165, NA, NA,
	"megaraptor", -90, -88, NA, NA,
	"megaraptora", -130, -66, "australovenator, fukuiraptor, megaraptor", NA,
	"megatheriidae", -29, -0.008, "megatherium", NA,
	"megatherium", -5, -0.01, NA, NA,
	"mesosauria", -299, -270.6, NA, NA,
	"metatheria", -125, -125, "marsupalia, sparassodonta, stagodontidae", NA,
	"metoposaurus", -227, -216.5, NA, NA,
	"metriacanthosauridae", -174, -125, NA, "'moderately-spined lizards'",
	"metriorhynchidae", -168, -125, "metriorhynchus, thalattosuchus", NA,
	"metriorhynchus", -157, -150, NA, NA,
	"microraptor", -125, -120, NA, NA,
	"moeritherium", -37, -35, NA, NA,
	"monotremata", -125, 0, "ornithorhynchidae, tachyglossidae", NA,
	"morganucodonta", -210, -140, NA, NA,
	"mosasauria", -121, -66, "mosasaurus, tylosaurus", NA,
	"mosasaurus", -82.7, -66, NA, NA,
	"moschops", -265, -260, NA, NA,
	"multituberculata", -166, -40, NA, NA,
	"mysticeti", -34, 0, NA, NA,
	"neoaves", -62.5, -62.5, "phorusrhacidae", NA,
	"neognathae", -72, -72, "galloanserae, neoaves", NA,
	"neovenator", -130, -125, NA, NA,
	"noasauridae", -164, -66, NA, NA,
	"nodosauridae", -155, -66, "edmontonia, europelta, nodosaurus, polacanthus, sauropelta", NA,
	"nodosaurus", -99.7, -86.3, NA, NA,
	"nothosauroidea", -251, -210, NA, NA,
	"notosuchia", -167, -11, "notosuchus, sebecidae, simosuchus", NA,
	"notosuchus", -85, -85, NA, NA,
	"odontoceti", -33.9, 0, NA, NA,
	"ophiacodontidae", -308, -273, NA, NA,
	"ornithischia*", -235, -235, "heterodontosaurus, marginocephalia, ornithopoda, thyreophora", NA,
	"ornithocheiridae", -140, -90, NA, NA,
	"ornithocheiroidea", -145, -145, "anhangueridae, azhdarchidae, ornithocheiridae, pteranodontia", NA,
	"ornitholestes", -154, -154, NA, NA,
	"ornithomimidae", -96, -66, "gallimimus, ornithomimus, struthiomimus", NA,
	"ornithomimosauria", -140, -66, "deinocheiridae, ornithomimidae", NA,
	"ornithomimus", -76.5, -66, NA, NA,
	"ornithopoda*", -170, -66, "camptosaurus, dryosauridae, hadrosauridae, hypsilophodon, iguanodon, mantellisaurus", NA,
	"ornithorhynchidae", -26, 0, NA, NA,
	"ornithosuchidae", -228, -203.6, NA, NA,
	"oviraptor", -75, -71, NA, NA,
	"oviraptoridae", -84, -66, "oviraptor", NA,
	"pachycephalosauria", -100, -66, "pachycephalosaurus", NA,
	"pachycephalosaurus", -70, -66, NA, NA,
	"pachypleurosauria", -251, -227, NA, NA,
	"pachyrhinosaurus", -73.5, -69, NA, NA,
	"pakicetus", -50, -48, NA, NA,
	"palaeognathae", -60, -60, "aepyornithiformes, apterygidae, casuariiformes, dinornithiformes, rheidae, struthionidae", NA,
	"palaeoloxodon", -2.58, -0.0117, NA, NA,
	"pantestudines", -240, -240, "testudinata", NA,
	"paraceratheriidae", -47, -23, "paraceratherium", NA,
	"paraceratherium", -34, -23, NA, NA,
	"parareptilia", -306, -306, "mesosauria, pareiasauria", NA,
	"parasaurolophus", -76.9, -73.5, NA, NA,
	"paraves*", -167, -167, "avialae, deinonychosauria, scansoriopterygidae", NA,
	"pareiasauria", -265, -252, NA, NA,
	"patagotitan", -101.62, -101.62, NA, NA,
	# perissodactyla : Tapiridae, Rhinocerotidae
	"perissodactyla*", -60, 0, "brontotheriidae, chalicotheriidae, equidae, paraceratheriidae", NA,
	"pholidosauridae", -150, -66, "sarcosuchus", NA,
	"phorusrhacidae", -43, -0.1, NA, "terror bids",
	"phytosauria", -242, -201.4, "leptosuchus, smilosuchus", NA,
	"pilosa", -55.8, 0, "megatheriidae", "sloths and anteaters",
	"pistosauroidea", -251, -251, "pistosaurus, plesiosauria", NA,
	"pistosaurus", -247.2, -237, NA, NA,
	"placentalia*", -90, -90, "afrotheria, euarchontoglires, laurasiatheria, xenarthra", NA,
	"placerias", -230, -215, NA, NA,
	"placodontia", -245, -201.3, NA, NA,
	"plateosaurus", -227, -204, NA, NA,
	"plesiosauria*", -232, -232, "cryptoclididae, elasmosauridae, leptocleididae, plesiosauridae, pliosauridae", NA,
	"plesiosauridae", -199.6, -174.7, NA, NA,
	"pliosauridae", -228, -89.3, "attenborosaurus, kronosaurus, liopleurodon, pliosaurus", NA,
	"pliosaurus", -155.7, -147, NA, NA,
	"polacanthus", -130, -125, NA, NA,
	"poposauridae", -237, -201.3, "poposaurus", "bipedal carnivores",
	"poposauroidea", -248, -248, "ctenosauriscidae, lotosaurus, poposauridae, shuvosauridae", NA,
	"poposaurus", -237, -216, NA, NA,
	"postosuchus*", -237, -201.4, NA, NA,
	"prestosuchidae", -247, -225, "prestosuchus, saurosuchus", NA,
	"prestosuchus", -242, -235, NA, NA,
	"primates", -65.9, 0, NA, NA,
	"prionosuchus", -299, -272, NA, NA,
	"proboscidea", -60, 0, "deinotheriidae, elephantidae, gomphotheriidae, moeritherium, stegodon", NA,
	"protoceratops", -75, -71, NA, NA,
	# "protoceratopsidae", -75, -71, NA, NA,
	"pseudosuchia", -248, -248, "aetosauria, batrachotomus, crocodylomorpha, gracilisuchidae, ornithosuchidae, phytosauria, poposauroidea, prestosuchidae, rauisuchia", NA,
	"psittacosaurus", -125, -105, NA, NA,
	"pteranodontia", -92, -66, NA, NA,
	"pterodactyloidea", -162.7, -162.7, "ornithocheiroidea, pterodactylus", NA,
	"pterodactylus", -150.8, -148.5, NA, "winged finger",
	"pterosauria", -228, -228, "dimorphodontidae, pterodactyloidea, rhamphorhynchidae", NA,
	"pyroraptor", -72, -72, NA, NA,
	"rauisuchia", -240, -200, "postosuchus, rauisuchus", NA,
	"rauisuchus", -235, -228, NA, NA,
	"reptiliomorpha", -340, -340, "amniota, diadectidae, seymouriamorpha", NA,
	"rhamphorhynchidae", -182, -148.5, NA, NA,
	"rheidae", -56, 0, NA, NA,
	"rhynchocephalia", -240, 0, NA, NA,
	"rhynchosauria", -251.5, -225, NA, NA,
	"rodentia", -59, 0, NA, NA,
	"rodhocetus", -47, -46, NA, NA,
	"saltasauridae", -85.8, -66, "alamosaurus, saltasaurus", NA,
	"saltasaurus", -70, -68, NA, NA,
	"sarcosuchus", -133, -112, NA, NA,
	"sauria", -265.8, 0, "archelosauria, lepidosauromorpha", NA,
	"saurischia*", -237, -237, "sauropodomorpha, theropoda", NA,
	"sauropelta", -108.5, -108.5, NA, NA,
	"sauropoda", -228, -66, "brachiosauridae, camarasaurus, cetiosauridae, diplodocidae, euhelopodidae, mamenchisauridae, titanosauria, vulcanodontidae", NA,
	"sauropodomorpha*", -235, -66, "massospondylidae, plateosaurus, sauropoda, thecodontosaurus", NA,
	"sauropsida", -311, -311, "eureptilia, parareptilia", NA,
	"sauropterygia*", -255, -255, "nothosauroidea, pachypleurosauria, pistosauroidea, placodontia", NA,
	"saurosuchus", -231.4, -225, NA, NA,
	"scansoriopterygidae", -165, -156, "epidexipteryx, scansoriopteryx", "'climbing wings', China",
	"scansoriopteryx", -165, -156, NA, NA,
	"scelidosaurus", -196.5, -183, NA, NA,
	"sebecidae", -67.6, -11.8, "barinasuchus, sebecus", "the latest surviving group of non-crocodilian crocodylomorphs",
	"sebecus", -59.4, -37.2, NA, NA,
	"serpentes", -94, 0, NA, NA,
	"seymouriamorpha", -305, -295, "seymouria", NA,
	"seymouria", 295, NA, NA, NA,
	"shantungosaurus", -85, -75, NA, NA,
	"shuvosauridae", -235, -201.3, NA, "theropod-like pseudosuchians",
	"simosuchus", -70, -66, NA, NA,
	"sinosauropteryx", -124.6, -122, NA, NA,
	"sirenia", -55.8, 0, NA, NA,
	"smilodon", -2.5, -0.01, NA, NA,
	"smilosuchus", -221.5, -205.6, NA, NA,
	"sparassodonta", -66, -2.58, "borhyaenidae, thylacosmilidae", NA,
	"sphenacodon", -300, -280, NA, "'wedge point tooth'",
	"sphenacodontia", -304, -304, "sphenacodontidae, therapsida", NA,
	"sphenacodontidae*", -302, -272, "dimetrodon, sphenacodon", NA,
	"sphenosuchia", -228, -152, "sphenosuchus", NA,
	"sphenosuchus", -195, -195, NA, NA,
	"spinosauridae", -139, -139, "baryonyx, irritator, spinosaurus", NA,
	"spinosaurus", -100, -94, NA, "'spine lizard', North Africa",
	"squamata", -168, 0, "chamaeleonidae, gekkota, mosasauria, serpentes, varanidae", NA,
	"stagodontidae", -92, -66, "didelphodon", NA,
	"staurikosaurus", -233.23, -228, NA, NA,
	"stegocephalia", -375, -375, "acanthostega, elginerpeton, ichthyostega, tiktaalik", NA,
	"stegodon", -11.6, -0.01, NA, NA,
	"stegosauria", -169, -100.5, "dacentrurus, kentrosaurus, stegosaurus", NA,
	"stegosaurus", -155, -145, NA, NA,
	"stokesosaurus", -156.5, -150, NA, NA,
	"struthiomimus", -77, -66, NA, NA,
	"struthionidae", -21, 0, NA, NA,
	"styracosaurus", -75.5, -74.5, NA, NA,
	"synapsida", -318, 0, "edaphosauridae, ophiacodontidae, sphenacodontia, varanopidae", NA,
	"tachyglossidae*", -5.333, 0, NA, NA,
	"tarbosaurus", -70, -68, NA, NA,
	"tawa", -215, -215, NA, NA,
	"teleosauridae", -183, -145, "teleosaurus", NA,
	"teleosaurus", -171, -164, NA, NA,
	"temnospondyli", -330, -330, "archegosauridae, eryops, lissamphibia, metoposaurus", NA,
	"testudinata", -210, 0, NA, NA,
	"tetanurae*", -201, -201, "carnosauria, coelurosauria, megalosauroidea", NA,
	"tetrapoda", -370, -370, "lepospondyli, reptiliomorpha, temnospondyli", NA,
	"tetrapodomorpha", -409, -409, "stegocephalia, tetrapoda", NA,
	"thalattosauria", -247, -201.4, NA, NA,
	"thalattosuchia", -201, -100, "metriorhynchidae, teleosauridae", NA,
	"thalattosuchus", -166, -160, NA, NA,
	"thecodontosaurus", -234, -234, NA, NA,
	"therapsida*", -285, -285, "dicynodontia, dinocephalia, theriodontia", NA,
	"theria*", -130, -130, "eutheria, metatheria", NA,
	"theriodontia*", -275, -275, "cynodontia, gorgonopsia, therocephalia", NA,
	"therizinosauridae*", -100, -66, "therizinosaurus", NA,
	"therizinosaurus", -70, -70, NA, NA,
	"therocephalia", -266, -242, NA, "'beast head'",
	"theropoda*", -236, -236, "ceratosauria, coelophysoidea, eodromaeus, eoraptor, herrerasauridae, tawa, tetanurae", NA,
	"thylacinidae", -28, -8e-05, NA, NA,
	"thylacoleonidae*", -27, -0.0117, NA, NA,
	"thylacosmilidae", -21, -3, "thylacosmilus", NA,
	"thylacosmilus", -9, -3, NA, NA,
	"thyreophora", -201, -201, "ankylosauria, scelidosaurus, stegosauria", NA,
	"tiktaalik", -375, -375, NA, NA,
	"titanosauria", -140, -66, "argentinosaurus, dreadnoughtus, patagotitan, saltasauridae", NA,
	"torvosaurus", -165, -148, NA, NA,
	"triceratops", -68, -66, NA, NA,
	"troodon", -77.5, -76.5, NA, "'wounding tooth', USA (Montana)",
	"troodontidae", -150, -66, "troodon", NA,
	"tylosaurus", -92.1, -66, NA, NA,
	"tyrannosauridae", -81.9, -66, "albertosaurus, alioramus, daspletosaurus, gorgosaurus, tarbosaurus, tyrannosaurus", NA,
	"tyrannosauroidea", -166, -66, "dilong, eotyrannus, megaraptora, stokesosaurus, tyrannosauridae, yutyrannus", NA,
	"tyrannosaurus", -72.7, -66, NA, NA,
	"tyrannotitan", -113, -100.5, NA, "'tyrant titan', Argentina",
	"urodela", -168, 0, NA, "salamanders",
	"ursidae", -38, 0, NA, NA,
	"utahraptor", -139, -134.6, NA, NA,
	"vancleavea", -228, -201.3, NA, NA,
	"varanidae", -80, 0, NA, NA,
	"varanopidae", -309, -260, NA, NA,
	"velociraptor", -75, -71, NA, NA,
	"vulcanodontidae", -199, -175, NA, NA,
	"xenarthra", -60, -60, "cingulata, pilosa", NA,
	"yutyrannus", -125, -125, NA, NA,
) %>%
	mutate(to = ifelse(is.na(to), from, to)) %>%
	mutate(across(c(from, to), ~-abs(.x))) %>%
	# mutate(children = children %>% map_chr(function(x) str_to_lower(str_c(sort(x), collapse=', ')))) %>%
	mutate(across(c(taxon, children), str_to_lower)) %>%
	select(taxon, from, to, children, notes) %>%
	arrange(taxon)

# print(df)

df %>% write_tsv('inst/extdata/tree_data.tsv')

# df[df$taxon %in% df$taxon[duplicated(str_remove(df$taxon, '\\*'))], ] %>% print()

# children = unlist(map(df$children, str_split, ', '))
# children = discard(unique(children[duplicated(children)]), is.na)
# children
# i = df$children %>% map_lgl(function(x) any(str_split(x, ', ') %in% children))
# df[i, ] %>% print

# cat('\n')
# cat('df = tribble(')
# cat('\n')
# cat('~taxon, ~from, ~to, ~children, ~notes,')
# cat('\n')
# for (i in 1:nrow(df)) { # i=1
# 	cat(
# 		paste0('"', df$taxon[i], '"'),
# 		df$from[i],
# 		df$to[i],
# 		df$children[i] %>% {ifelse(. == '', NA, paste0('"', ., '"'))},
# 		df$notes[i] %>% {ifelse(. == '', NA, paste0('"', ., '"'))},
# 		sep = ', '
# 	)
# 	cat(', \n')
# }
# cat(')')
# cat('\n')

