suppressPackageStartupMessages({
	library(magrittr)
	library(tidyverse)
})

tips = tribble(
	~taxon                  , ~from, ~to, ~notes,
	# theropods
	'staurikosaurus'       , 233.23, 228, '',
	'herrerasaurus'        , 231.4 , 228.91, '',
	'eodromaeus'           , 231.4 , 229, "'dawn runner', Argentina",
	# 'coelophysoidea'       , 227   , 183, '',
	'coelophysis'          , 215   , 208.5, '',
	'dilophosaurus'        , 195.2 , 183.7, "two-crested lizard",
	'ceratosaurus'         , 153   , 148, "'horn lizard', USA",
	'noasauridae'          , 164   ,  66, '',
	'abelisauridae'        , 143   ,  66, "'Abel's lizards'",
	'megalosauridae'       , 170   , 145, "incl. Megalosaurus, Torvosaurus",
	'baryonyx'             , 130   , 125, "'heavy claw', UK",
	'spinosaurus'          , 100   ,  94, "'spine lizard', North Africa",
	'allosaurus'           , 155   , 143.1, '',
	'metriacanthosauridae' , 174   , 125, "'moderately-spined lizards'",
	'tyrannotitan'         , 113   , 100.5, "'tyrant titan', Argentina",
	'giganotosaurus'       ,  99.6 ,  95, "'giant southern lizard', Argentina",
	'carcharodontosaurus'  , 100   ,  94, "'jagged toothed lizard', Northwest Africa",
	# 'tyrannosauroidea'     , 166   ,  66,
	'tyrannosauridae'      ,  81.9 ,  66, '',
	'ornitholestes'        , 154   , 154, '',
	'compsognathidae'      , 151.5 , 108, "incl. Compsognathus, Sinosauropteryx",
	# 'ornithomimosauria'    , 140   ,  66,
	'ornithomimidae'       ,  96   ,  66, '',
	'deinocheiridae'       , 115   ,  69, '',
	'alvarezsauroidea'     , 160   ,  66, '',
	'therizinosauria'      , 145   ,  66, '',
	'oviraptorosauria'     , 130   ,  66, '',
	'troodontidae'         , 150   ,  66, "'wounding tooth', USA (Montana), incl. Troodon",
	'deinonychus'          , 115   , 108, '',
	'velociraptor'         ,  75   ,  71, '',
	'scansoriopterygidae'  , 165   , 156, "'climbing wings', China, incl. Scansoriopteryx, Epidexipteryx",
	'microraptor'          , 125   , 120, '',
	'archaeopteryx'        , 150.8 , 148.5, "'old-wing', Southern Germany",
	'enantiornithes'       , 136   ,  66, "'opposite birds'",
	'ichthyornis'          ,  95   ,  83.5, '',
	'hesperornis'          ,  83.6 ,  72, '',

	# aves
	'galloanserae'         , 72    ,   0, "maastrichtian",
	'phorusrhacidae'       ,  43   ,   0.1, "terror bids",
	'rheidae'              ,  56   ,   0, '',
	'casuariiformes'       ,  23   ,   0, "cassowarys and emus",
	'apterygidae'          ,  23   ,   0, "kiwis",
	'struthionidae'        ,  21   ,   0, '',
	'dinornithiformes'     ,  17   , 0.0006, "moas, incl Dinornis",
	'aepyornithiformes'    , 2.58  , 0.001, " elephant birds, incl Aepyornis",

	# sauropodomorpha
	'massospondylidae'   , 227   , 176, '',
	'plateosauridae'     , 225   , 190, '',
	# 'sauropoda'          , 228   ,  66,
	'vulcanodontidae'    , 199   , 175, '',
	'mamenchisauridae'   , 184.5 , 114, '',
	'cetiosauridae'      , 178   , 161, '',
	'diplodocidae'       , 170   , 136.4, '',
	'brachiosauridae'    , 160   , 100, '',
	'camarasauridae'     , 155   , 145, '',
	'euhelopodidae'      , 145   ,  88, '',
	'titanosauria'       , 140   ,  66, '',

	'heterodontosauridae', 201   , 140, '',
	'scelidosaurus'      , 196.5 , 183, '',
	'stegosauria'        , 169   , 100.5, '',
	'nodosauridae'       , 155   ,  66, "incl. Polacanthus",
	'ankylosauridae'     , 122   ,  66, '',
	# 'ornithopoda'        , 164   ,  66,
	'dryosauridae'       , 164   , 115, '',
	'hypsilophodontidae' , 130   , 125, '',
	'iguanodontidae'     , 126   , 122, '',
	'hadrosauridae'      ,  86   ,  66, '',
	# 'ceratopsia'         , 161   ,  66,
	'psittacosaurus'     , 125   , 105, '',
	'ceratopsidae'       ,  82   ,  66, '',
	'protoceratopsidae'  ,  75   ,  71, '',
	'pachycephalosauria' , 100   ,  66, '',

	# pterosauria
	'dimorphodontidae'   , 208   , 182, '',
	'rhamphorhynchidae'  , 182   , 148.5, '',
	'pterodactylus'      , 150.8 , 148.5, "winged finger",
	'ornithocheiridae'   , 140   ,  90, '',
	'anhangueridae'      , 140   ,  92.5, '',
	'azhdarchidae'       ,  92   ,  66, "includes Quetzalcoatlus",
	'pteranodontia'      ,  92   ,  66, '',

	# pseudosuchia
	'ctenosauriscidae'   , 247.5 , 237, "all species had large 'sails' on their backs",
	'poposauridae'       , 237   , 201.3, "bipedal carnivores",
	'shuvosauridae'      , 235   , 201.3, "theropod-like pseudosuchians",
	'prestosuchidae'     , 247   , 225, '',
	'phytosauria'        , 242   , 201.4, '',
	'rauisuchia'         , 240   , 200, '',
	'aetosauria'         , 231.4 , 201.4, '',
	'saurosuchus'        , 231.4 , 225, '',
	'ornithosuchidae'    , 228   , 203.6, '',
	'sphenosuchia'       , 228   , 152, '',
	# 'thalattosuchia'     , 201   , 100,
	'teleosauridae'      , 183   , 145, '',
	'metriorhynchidae'   , 168   , 125, '',
	'sarcosuchus'        , 133   , 112, '',
	'sebecidae'          ,  67.6 , 11.8, "the latest surviving group of non-crocodilian crocodylomorphs",
	'alligatoroidea*'    ,  78   ,   0, "campanian",
	'crocodyloidea*'     ,  70   ,   0, "maastrichtian",
	'gavialoidea*'       ,  70   ,   0, "maastrichtian",
	'rhynchosauria'      , 251.5 , 225, '',
	'ichthyosauromorpha' , 251.3 ,  90, '',
	'nothosauroidea'     , 251   , 210, '',
	'pachypleurosauria'  , 251   , 227, '',
	'placodontia'        , 245   , 201.3, '',
	'pistosaurus'        , 247.2 , 237, '',
	'pliosauridae'       , 228   ,  89.3, "incl. Liopleurodon (166–155) Pliosaurus (155.7–147) Kronosaurus (125–99.6)",
	'plesiosauridae'     , 199.6 , 174.7, '',
	'leptocleididae'     , 145   , 100.5, '',
	'elasmosauridae'     , 130   ,  66, '',
	'thalattosauria'     , 247   , 201.4, '',
	'araeoscelidia'      , 302   , 275.6, '',
	'testudinata'        , 210   ,   0, '',
	'rhynchocephalia'    , 240   ,   0, '',
	'mosasauria'         , 121   ,  66, '',
	'gekkota'            , 100   ,   0, '',
	'varanidae'          ,  80   ,   0, '',
	'chamaeleonidae'     ,  26   ,   0, '',
	'snakes'             ,  94   ,   0, '',
	'mesosauria'         , 299   , 270.6, '',
	'pareiasauria'       , 265   , 252, '',

	# synapsids
	'ophiacodontidae'    , 308   , 273, '',
	'edaphosauridae'     , 307   , 272, '',
	'diadectidae'        , 305   , 256, "incl. diadectes = 'crosswise-biter' one of the first herbivorous tetrapods, one of the first fully terrestrial vertebrates to attain large size",
	'sphenacodontidae'   , 300   , 272, "'wedge point tooth family' includes Dimetrodon",
	# 'dinocephalia'       , 279   , 260, "'terrible head'
	'moschops'           , 265   , 260, '',
	'gorgonopsia'        , 270   , 252, '',
	'dicynodontia'       , 268   , 201.4, "'two dog tooth' includes Lystrosaurus",
	'therocephalia'      , 266   , 242, "'beast head'",
	'morganucodonta'     , 210   , 140, '',
	'multituberculata'   , 166   ,  40, '',
	'monotremata'        , 125   ,   0, '',
	'marsupalia'         ,  66   ,   0, '',
	'proboscidea'        ,  60   ,   0, '',
	'sirenia'            ,  55.8 ,   0, '',
	'cingulata'          ,  58.7 ,   0, "armadillos including Glyptodont",
	'pilosa'             ,  55.8 ,   0, "sloths and anteaters",
	'chiroptera'         ,  56   ,   0, '',
	'carnivora'          ,  51.88,   0, '',
	'hyaenodontidae'     ,  55.2 ,  16.9, '',
	'perissodactyla'     ,  56   ,   0, "Tapiridae, Brontotheriidae, Equidae, Chalicotheriidae, Rhinocerotidae, Paraceratheriidae",
	'basilosauridae'     ,  43   ,  33.9, '',
	'mysticeti'          ,  56   ,   0, '',
	'odontoceti'         ,  33.9 ,   0, '',
	'andrewsarchus'      ,  47.8 ,  37.71, '',
	'entelodontidae'     ,  37.2 ,  15.97, '',
	'lagomorpha'         ,  59   ,   0, '',
	'rodentia'           ,  59   ,   0, '',
	'primates'           ,  65.9 ,   0, '',
	# 'sauria', 268.5, 0,
	# 'paraceratherium', 34, 23,
	# 'chalicotherioidea', 48.6  , 0.005,
	# 'equidae', 55.8, 0,
	# 'phorusrhacidae', 43, 0.1,

	# 'lepospondyli'     , 339   , 251.902, '',
	'eryops'           , 299   , 273, '',
	'archegosauridae'  , 297   , 252, "includes Prionosuchus",
	'gymnophiona'      , 223   ,   0, "caecilian",
	'anura'            , 200   ,   0, "frogs and toads",
	'urodela'          , 168   ,   0, "salamanders",
	'diplocaulus'      , 306   , 255, '',
    'tiktaalik'        , 375   , NA, '',
    'elginerpeton'     , 375   , NA, '',
    'ichthyostega'     , 365   , 360, '',
    'acanthostega'     , 365   , NA, '',
    # 'Ichthyostegalia'  , 368   , 329,
) %>%
	mutate(to = if_else(is.na(to), from, to))

tips

relations = tribble(
	~taxon             , ~from , ~to, ~children,

	'aves*'            ,  75   , NA , c('neognathae', 'palaeognathae'),
	'neognathae'       ,  72   , NA , c('galloanserae', 'neoaves'),
	'neoaves'          , 62.5  , NA , c('phorusrhacidae'),
	'palaeognathae'    ,  60   , NA , c('rheidae', 'casuariiformes', 'apterygidae', 'struthionidae', 'dinornithiformes', 'aepyornithiformes'),

	'afrotheria'       ,  65   , NA , c('proboscidea', 'sirenia'),
	'amniota'          , 323   , NA , c('sauropsida', 'synapsida'),
	'ankylosauria'     , 167   , NA , c('nodosauridae', 'ankylosauridae'),
	'anomodontia'      , 270   , NA , c('dicynodontia'),
	'archelosauria'    , 260   , NA , c('archosauromorpha', 'pantestudines'),
	'artiodactyla'     , 56    , NA , c('cetacea', 'andrewsarchus', 'entelodontidae'),
	'archosauria'      , 248   , NA , c('avemetatarsalia', 'pseudosuchia'),
	'archosauromorpha' , 260   , NA , c('rhynchosauria', 'archosauria', 'ichthyosauromorpha', 'sauropterygia', 'thalattosauria'),
	# 'avemetatarsalia'  , 247   , NA , c('dinosauromorpha', 'pterosauria'),
	'avemetatarsalia'  , 247   , NA , c('dinosauria', 'pterosauria'),
	'cetacea'          ,  56   , NA , c('basilosauridae', 'odontoceti', 'mysticeti'),
	'crocodylomorpha'  , 235   , NA , c('sphenosuchia', 'crocodyliformes', 'thalattosuchia'),
	'crocodyliformes'  , 225   , NA , c('crocodilia', 'sarcosuchus', 'sebecidae'),
	'crocodilia'       , 100   , NA , c('alligatoroidea', 'crocodyloidea', 'gavialoidea'),
	'cynodontia'       , 260   , NA , c('mammalia', 'morganucodonta'),
	# 'dinosauromorpha'  , 247   , NA , c('dinosauria'),
	'dinosauria*'      , 240   , NA , c('saurischia', 'ornithischia'),
	'euarchontoglires' ,  66   , NA , c('lagomorpha', 'rodentia', 'primates'),
	'eureptilia'       , 311   , NA , c('diapsida', 'araeoscelidia'),
	'diapsida'         , 302   , NA , c('sauria'),
	# 'eutheria'        , 125   , NA , c('placentalia'),
	'laurasiatheria'   ,  65   , NA , c('chiroptera', 'carnivora', 'perissodactyla', 'artiodactyla', 'hyaenodontidae'),
	'lepidosauromorpha', 252   , NA , c('squamata', 'rhynchocephalia'),
	'lizards'          , 168   , NA , c('mosasauria', 'varanidae', 'gekkota', 'chamaeleonidae'),
	'mammalia'         , 225   , NA , c('theria', 'monotremata', 'multituberculata'),
	'marginocephalia*' , 165   , NA , c('ceratopsia', 'pachycephalosauria'),
	'ceratopsia'       , 161   , NA , c('psittacosaurus', 'ceratopsidae', 'protoceratopsidae'),
	# 'metatheria'      , 125   , NA , c('marsupalia'),
	'ornithischia*'    , 235   , NA , c('thyreophora', 'heterodontosauridae', 'ornithopoda', 'marginocephalia'),
	'thyreophora'      , 201   , NA , c('scelidosaurus', 'ankylosauria', 'stegosauria'),
	'ornithocheiroidea', 145   , NA , c('ornithocheiridae', 'azhdarchidae', 'pteranodontia', 'anhangueridae'),
	'ornithopoda*'     , 170   , NA , c('dryosauridae', 'hypsilophodontidae', 'iguanodontidae', 'hadrosauridae'),
	'pantestudines'    , 240   , NA , c('testudinata'),
	'placentalia*'     ,  90   , NA , c('xenarthra', 'afrotheria', 'laurasiatheria', 'euarchontoglires'),
	'parareptilia'     , 306   , NA , c('pareiasauria', 'mesosauria'),
	'poposauroidea'    , 248   , NA , c('poposauridae', 'shuvosauridae', 'ctenosauriscidae'),
	'pistosauroidea'   , 251   , NA , c('pistosaurus', 'plesiosauria'),
	'plesiosauria*'    , 232   , NA , c('pliosauridae', 'plesiosauridae', 'elasmosauridae', 'leptocleididae'),
	'pseudosuchia'     , 248   , NA , c('saurosuchus', 'prestosuchidae', 'poposauroidea', 'ornithosuchidae', 'phytosauria', 'aetosauria', 'rauisuchia', 'crocodylomorpha'),
	'pterosauria'      , 228   , NA , c('pterodactyloidea', 'dimorphodontidae', 'rhamphorhynchidae'),
	'pterodactyloidea' , 162.7 , NA , c('pterodactylus', 'ornithocheiroidea'),
	'sauria'           , 265.8 , NA , c('lepidosauromorpha', 'archelosauria'),
	'saurischia*'      , 237   , NA , c('sauropodomorpha', 'theropoda'),
	'sauropodomorpha'  , 230   , NA , c('massospondylidae', 'plateosauridae', 'sauropoda'),
	'sauropoda'        , 201   , NA , c('vulcanodontidae', 'mamenchisauridae', 'cetiosauridae', 'diplodocidae', 'brachiosauridae', 'camarasauridae', 'euhelopodidae', 'titanosauria'),
	'sauropsida'       , 311   , NA , c('parareptilia', 'eureptilia'),
	'sauropterygia*'   , 255   , NA , c('nothosauroidea', 'pachypleurosauria', 'placodontia', 'pistosauroidea'),
	'sphenacodontia'   , 304   , NA , c('sphenacodontidae', 'therapsida'),
	'squamata'         , 168   , NA , c('lizards', 'snakes'),
	'synapsida'        , 318   , NA , c('edaphosauridae', 'diadectidae', 'ophiacodontidae', 'sphenacodontia'),

	# theropods
	'theropoda*'       , 236   , NA , c('herrerasauridae', 'eodromaeus', 'coelophysoidea', 'ceratosauria', 'tetanurae'),
	'coelophysoidea'   , 227   , 183, c('dilophosaurus', 'coelophysis'),
	'herrerasauridae'  , 233.23, NA , c('herrerasaurus', 'staurikosaurus'),
	'megalosauroidea*' , 175   , NA , c('spinosauridae', 'megalosauridae'),
	'spinosauridae'    , 139   , NA , c('spinosaurus', 'baryonyx'),
	'ceratosauria'     , 199.3 , NA , c('ceratosaurus', 'noasauridae', 'abelisauridae'),
	'tetanurae*'       , 201   , NA , c('megalosauroidea', 'carnosauria', 'coelurosauria'),
	'tetrapoda'        , 370   , NA , c('amniota', 'temnospondyli', 'lepospondyli'),
	'carnosauria*'     , 180   , NA , c('allosauridae', 'metriacanthosauridae', 'carcharodontosauridae'),
	'allosauridae'     , 179.17, NA , c('allosaurus'),
	'carcharodontosauridae',154, NA , c('carcharodontosaurus', 'giganotosaurus', 'tyrannotitan'),
	'paraves*'         , 167   , NA , c('scansoriopterygidae', 'deinonychosauria', 'avialae'),
	'deinonychosauria' , 167   , NA , c('dromaeosauridae', 'troodontidae'),
	'maniraptora*'     , 167   , NA , c('alvarezsauroidea', 'therizinosauria', 'oviraptorosauria', 'paraves'),
	'avialae'          , 150.8 , NA , c('archaeopteryx', 'enantiornithes', 'euornithes'),
	'euornithes'       , 130.7 , NA , c('aves', 'ichthyornis', 'hesperornis'),
	'coelurosauria*'   , 170   , NA , c('ornitholestes', 'tyrannosauroidea', 'maniraptora', 'compsognathidae', 'ornithomimosauria'),
	'ornithomimosauria', 140   , NA , c('ornithomimidae', 'deinocheiridae'),
	'dromaeosauridae'  , 145   , NA , c('deinonychus', 'velociraptor', 'microraptor'),
	'tyrannosauroidea' , 166   , NA , c('tyrannosauridae'),

	'thalattosuchia'   , 201   , NA , c('teleosauridae', 'metriorhynchidae'),
	'therapsida'       , 279.5 , NA , c('anomodontia', 'dinocephalia', 'gorgonopsia', 'cynodontia', 'therocephalia'),
	'dinocephalia'     , 279   , NA , c('moschops'),
	'theria*'           , 125   , NA , c('placentalia', 'marsupalia'),
	# 'theria*'          , 125   , NA , c('metatheria', 'eutheria'),
	'xenarthra'        ,  60   , NA , c('cingulata', 'pilosa'),

    'tetrapodomorpha'  , 409   , NA , c('tetrapoda', 'stegocephalia'),
	'stegocephalia'    , 375   , NA , c('tiktaalik', 'elginerpeton', 'ichthyostega', 'acanthostega'),
	'temnospondyli'    , 330   , NA , c('eryops', 'archegosauridae', 'lissamphibia'),
	'lissamphibia'     , 250   , NA , c('anura', 'urodela', 'gymnophiona'),
	'lepospondyli'     , 339   , NA , c('diplocaulus'),
)

relations

bind_rows(tips, relations) %>%
	mutate(across(c(from, to), ~-abs(.x))) %>%
	mutate(children = children %>% map_chr(function(x) str_to_lower(str_c(x, collapse=',')))) %>%
	mutate(across(c(taxon, children), str_to_lower)) %>%
	select(taxon, from, to, children, notes) %>%
	write_tsv('inst/extdata/tree_data.tsv')





