# suppressPackageStartupMessages({
# 	library(tidyverse)
# })

df = tibble::tribble(
	~taxon, ~from, ~to, ~children, ~notes, ~level,

	"abelisauridae", -143, -66, "abelisaurus, carnotaurus, majungasaurus, rugops", "'Abel's lizards'.", NA,
	'rugops', 95, NA, NA, "'Wrinkle face'. Africa.", 'genus',
	'majungasaurus', 70, 66, NA, "Named after the Mahajanga Province, northwestern Madagascar.", 'genus',
	"abelisaurus", -80, -80, NA, "'Abel's lizard'. South America.", NA,
	"acanthostega", -365, -365, NA, "'Spiny roof'. Greenland.", 'genus',
	"actinopterygii", -425, 0, NA, "Ray-finned fish", NA,
	"aepyornithiformes", -2.58, -0.001, NA, "Elephant birds. Madagascar. Aepyornis and Mullerornis.", NA,
	"aetosauria", -231.4, -201.4, "aetosaurus, desmatosuchus", "'Eagle lizards'.", NA,
	"aetosaurus", -227.3, -205.7, NA, "'Eagle lizard'.", NA,
	"afrotheria", -65, 0, "proboscidea, sirenia", "incl golden moles, elephant shrews, otter shrews, tenrecs, aardvarks, hyraxes, elephants, sea cows", NA,
	"alamosaurus", -70, -66, NA, "'Ojo Alamo lizard', named after the geologic formation it was found in. The only known titanosaur from North America.", NA,
	"albertosaurus", -71, -68, NA, "'Alberta lizard'. North America.", NA,
	"alioramus", -70, -70, NA, "'different branch'. Asia.", NA,
	"alligator", -37.2, 0, NA, NA, NA,
	"alligatoroidea", -83.6, 0, "alligator, caiman, deinosuchus", NA, NA,
	"allosauridae", -179.17, -145, "allosaurus", NA, NA,
	"allosaurus", -155, -143.1, NA, "'different lizard'.", NA,
	"alvarezsauridae", -97, -66, "alvarezsaurus", "'Alvarez's lizards'.", NA,
	"alvarezsaurus", -86, -83, NA, "'Alvarez's lizard'. Argentina.", NA,
	"ambulocetus", -48, -47, NA, NA, NA,
	"amniota", -323, 0, "sauropsida, synapsida", NA, NA,
	"andrewsarchus", -47.8, -37.71, NA, NA, 'genus',
	"anhangueridae", -140, -92.5, 'anhanguera', NA, NA,
	'anhanguera', 112, 92.5, NA, NA, 'genus',
	"ankylosauria", -167, -66, "ankylosauridae, nodosauridae", NA, NA,
	"ankylosauridae", -122, -66, "ankylosaurus, euoplocephalus", NA, NA,
	"ankylosaurus", -68, -66, NA, NA, NA,
	"anura", -200, 0, NA, "'Without tail'. Frogs and toads.", 'order',
	"apatosaurus", -152, -151, NA, NA, NA,
	"apterygidae", -23, 0, NA, "kiwis", NA,
	"araeoscelidia", -302, -275.6, NA, NA, NA,
	"archaeopteryx", -150.8, -148.5, NA, "'Old-wing'. Southern Germany", NA,
	"archegosauridae*", -305, -252, "archegosaurus, prionosuchus", 'Fully aquatic, metabolically and physiologically similar to fish than modern amphibians.', NA,
	"archegosaurus", -299, -253, NA, NA, 'genus',
	"archelosauria", -260, 0, "archosauromorpha, pantestudines", NA, NA,
	"archosauria", -248, 0, "avemetatarsalia, pseudosuchia", NA, NA,
	"archosauriformes", -252, 0, "archosauria, erythrosuchus, euparkeria, vancleavea, proterosuchidae", NA, NA,
	'proterosuchidae', 252, 247, NA, "'First crocodiles'.", 'genus',
	"archosauromorpha", -260, 0, "archosauriformes, ichthyosauromorpha, rhynchosauria, sauropterygia, thalattosauria, tanystropheus", NA, NA,
	# 'proterochampsidae',
	# 'tanystropheidae', 247.2, 201, NA, "Very long, stiff necks.", NA,
	'tanystropheus', 247, 237, NA, "'Long hinged'. Extremely long neck - longer than torso and tail combined.", 'genus',
	"argentinosaurus", -96.2, -92.19, NA, NA, NA,
	"artiodactyla", -60, 0, "andrewsarchus, cetacea, entelodontidae, hippopotamidae, tylopoda, suina, giraffidae, bovidae", NA, NA,
	'bovidae', 20, 0, NA, NA, NA,
	'giraffidae', 20, 0, 'giraffa, sivatherium', NA, NA,
	'giraffa', 11.61, 0, NA, NA, NA,
	'sivatherium', 7, 0.8, NA, NA, NA,
	'suina', 33.9, 0, NA, NA, NA,
	'tylopoda', 40, 0, NA, NA, NA,
	'hippopotamidae', 7.4, 0, NA, NA, NA,
	"atrociraptor", -72.2, -71.5, NA, NA, NA,
	"attenborosaurus", -196.5, -189.6, NA, NA, NA,
	"australovenator", -95, -95, NA, NA, NA,
	"avemetatarsalia", -247, 0, "dinosauromorpha, pterosauria", NA, NA,
	"aves", -75, 0, "neognathae, palaeognathae", NA, NA,
	"avialae", -150.8, 0, "archaeopteryx, enantiornithes, euornithes", NA, NA,
	"azhdarchidae", -92, -66, 'quetzalcoatlus, hatzegopteryx', NA, NA,
	'quetzalcoatlus', 68, 66, NA, "Name refers to the Aztec serpent god of the sky.", 'genus',
	'hatzegopteryx', 66, NA, NA, "Named after Hațeg, a town in Romania", 'genus',
	"barinasuchus", -42.2, -11.8, NA, NA, NA,
	"barosaurus", -152, -150, NA, NA, NA,
	"baryonyx", -130, -125, NA, "'heavy claw', UK", NA,
	"basilosauridae", -43, -33.9, "basilosaurus, dorudon, perucetus", NA, NA,
	'perucetus', 39.8, 37.84, NA, 'Peru', 'genus',
	"basilosaurus", -41.3, -33.9, NA, NA, NA,
	"batrachotomus", -242, -237, NA, NA, NA,
	"borhyaena", -21, -15.5, NA, NA, NA,
	"borhyaenidae", -63, -5.333, "borhyaena, lycopsis", NA, NA,
	"brachiosauridae", -160, -100, "brachiosaurus, giraffatitan", NA, NA,
	"brachiosaurus", -154, -150, NA, NA, NA,
	"brontosaurus", -156.3, -146.8, NA, NA, NA,
	"brontotheriidae", -56, -34, 'megacerops, rhinotitan, embolotherium', NA, NA,
	'embolotherium*', 40, NA, NA, NA, 'genus',
	'megacerops', 38, 33.9, NA, "'Large horn face' aka Brontotherium. North America.", 'genus',
	'rhinotitan', 48, 37.8, NA, "Mongolia.", 'genus',
	"caiman", -16, 0, NA, NA, NA,
	"camarasaurus", -155, -143.1, NA, NA, NA,
	"camptosaurus", -156.3, -146.8, NA, NA, NA,
	"canidae", -37.8, 0, NA, NA, NA,
	"carcharodontosauridae", -154, -90, "carcharodontosaurus, concavenator, giganotosaurus, neovenator, tyrannotitan, mapusaurus", NA, NA,
	'mapusaurus', 94, 90, NA, "Argentina. Name derived from Mapuche word Mapu, meaning 'of the Land' or 'of the Earth'", 'genus',
	"carcharodontosaurus", -100, -94, NA, "'jagged toothed lizard', Northwest Africa", NA,
	"carnivora", -51.88, 0, "canidae, felidae, ursidae", NA, NA,
	"carnosauria", -180, -90, "allosauridae, carcharodontosauridae, metriacanthosauridae", NA, NA,
	"carnotaurus", -72, -69, NA, "'Meat bull'. South America. Two thick horns above the eyes. Relatively short, deep snout. Small, vestigial forelimbs.", 'genus',
	"casuariiformes", -23, 0, NA, "cassowarys and emus", NA,
	"centrosaurus", -76.5, -75.5, NA, NA, NA,
	"ceratopsia", -161, -66, "ceratopsidae, protoceratops, psittacosaurus", NA, NA,
	"ceratopsidae", -90, -66, "centrosaurus, chasmosaurus, diabloceratops, pachyrhinosaurus, styracosaurus, triceratops", NA, NA,
	"ceratosauria", -199.3, -66, "abelisauridae, ceratosaurus, noasauridae", NA, NA,
	"ceratosaurus", -153, -148, NA, "'Horn lizard', USA. Ridge-like horn on midline of snout. Pair of horns over the eyes. Forelimbs short but fully functional.", 'genus',
	"cetacea", -56, 0, "ambulocetus, basilosauridae, mysticeti, odontoceti, pakicetus, rodhocetus", NA, NA,
	"cetiosauridae", -178, -161, "cetiosaurus", NA, NA,
	"cetiosaurus", -170, -164.7, NA, NA, NA,
	"chalicotheriidae", -48.6, -1.806, 'chalicotherium, moropus', NA, NA,
	'chalicotherium', 14, 5, NA, "'Gravel beast'.", 'genus',
	'moropus', 20.43, 13.6, NA, "'Slow foot'. North America", 'genus',
	"chamaeleonidae", -26, 0, NA, NA, NA,
	"chasmosaurus", -77, -76, NA, NA, NA,
	"chiroptera", -56, 0, NA, NA, NA,
	"chondrichthyes", -439, 0, "elasmobranchii", "cartilaginous fish", 'class',
	"cingulata", -58.7, 0, "glyptodontinae", "armadillos", NA,
	"coelophysis", -215, -208.5, NA, NA, NA,
	"coelophysoidea", -227, -183, "coelophysis, dilophosaurus", NA, NA,
	"coelurosauria", -170, 0, "compsognathidae, maniraptora, ornitholestes, ornithomimosauria, tyrannosauroidea", NA, NA,
	"compsognathidae", -151.5, -108, "compsognathus, sinosauropteryx", NA, NA,
	"compsognathus", -150.8, -145, NA, NA, NA,
	"concavenator", -125, -125, NA, NA, NA,
	"corythosaurus", -77, -75.7, NA, NA, NA,
	"crocodilia", -100, 0, "alligatoroidea, crocodyloidea, gavialoidea", NA, NA,
	"crocodylidae", -46, 0, "crocodylus", NA, NA,
	"crocodyliformes", -225, 0, "crocodilia, notosuchia, pholidosauridae", NA, NA,
	"crocodyloidea", -70, 0, "crocodylidae", NA, NA,
	"crocodylomorpha", -235, 0, "crocodyliformes, sphenosuchia, thalattosuchia", NA, NA,
	"crocodylus", -25, 0, NA, NA, NA,
	"cryptoclididae", -170, -130, "cryptoclidus, kimmerosaurus", NA, NA,
	"cryptoclidus", -166, -160, NA, NA, NA,
	"ctenosauriscidae", -247.5, -237, NA, "all species had large 'sails' on their backs", NA,
	"cynodontia", -260, 0, "cynognathus, thrinaxodon, mammaliamorpha", "'Dog teeth'.", NA,
	'thrinaxodon', 252, 247, NA, "'Trident tooth'.", 'genus',
	"cynognathus", -247, -237, NA, NA, NA,
	"dacentrurus", -154, -140, NA, NA, NA,
	"daspletosaurus", -78, -74.4, NA, NA, NA,
	"deinocheiridae", -115, -69, "deinocheirus", NA, NA,
	"deinocheirus", -70, -70, NA, NA, NA,
	"deinonychosauria", -167, -66, "dromaeosauridae, troodontidae", NA, NA,
	"deinonychus", -115, -108, NA, NA, NA,
	"deinosuchus", -82, -73, NA, NA, NA,
	"deinotheriidae", -28, -1, "deinotherium", "'Terrible beasts'.", NA,
	"deinotherium", -13, -1, NA, "'Terrible beast'. East Africa, Europe, India. Tusks grew down and curved back from lower jaw.", 'genus',
	"desmatosuchus", -228, -210, NA, NA, NA,
	"diabloceratops", -81.4, -81, NA, NA, NA,
	"diadectes", -290, -272, NA, "'Crosswise-biter'.", 'genus',
	"diadectidae", -305, -256, "diadectes, diasparactus", "'Crosswise-biters'. The first herbivorous tetrapods, the first fully terrestrial vertebrates to attain large size", NA,
	"diapsida", -302, 0, "sauria", NA, NA,
	"diasparactus", -296.4, -295, NA, NA, 'genus',
	"dicynodontia", -268, -201.4, "lisowicia, lystrosaurus, placerias", "'two dog tooth'.", NA,
	"didelphodon", -73, -66, NA, NA, NA,
	"dilong", -130, -122.5, NA, NA, NA,
	"dilophosaurus", -195.2, -183.7, NA, "two-crested lizard", NA,
	"dimetrodon", -295, -270, NA, "'Two measures tooth'. Large neural spine sail.", 'genus',
	'dimorphodon', 201.3, 189.6, NA, "'Two shape tooth'. Europe", 'genus',
	"dinocephalia", -279, -260, "moschops, titanophoneus", "'terrible head'.", NA,
	'titanophoneus', 268, 265, NA, "'Titanic murderer'", 'genus',
	"dinornithiformes", -17, -6e-04, NA, "Moas. New Zealand. 9 species 6 genera incl Dinornis", NA,
	"dinosauria", -240, 0, "ornithischia, saurischia", NA, NA,
	"dinosauromorpha", -247, 0, "dinosauria", NA, NA,
	"diplocaulus", -306, -255, NA, "'Double stalk'. Largest and best-known lepospondyl, distinctive boomerang-shaped skull.", 'genus',
	"diplodocidae", -170, -136.4, "apatosaurus, barosaurus, brontosaurus, diplodocus", NA, NA,
	"diplodocus", -154, -152, NA, NA, NA,
	"diprotodon", -1.77, -0.04, NA, NA, NA,
	"diprotodontidae", -28.4, -0.04, "diprotodon", "giant wombats", NA,
	"dorudon", -41.03, -33.9, NA, NA, NA,
	"dreadnoughtus", -76, -70, NA, NA, NA,
	"dromaeosauridae", -145, -66, "eudromaeosauria, microraptoria", NA, NA,
	'microraptoria', 126, 113, "microraptor, sinornithosaurus", NA, NA,
	'sinornithosaurus', 124.6, 122, NA, "'Chinese bird-lizard'", 'genus',
	"dromaeosaurus", -80, -69.1, NA, NA, NA,
	"dryosauridae", -164, -115, "dryosaurus", NA, NA,
	"dryosaurus", -155, -145, NA, NA, NA,
	"edaphosauridae", -307, -272, "edaphosaurus, lupeosaurus", NA, NA,
	'lupeosaurus', 295, NA, NA, NA, 'genus',
	"edaphosaurus", -303.4, -272.5, NA, "'Pavement lizard'. North America, Europe. Large dorsal sail. One of the earliest-known, large, herbivorous amniotes.", NA,
	"edmontonia", -76.5, -69, NA, NA, NA,
	"edmontosaurus", -73, -66, NA, NA, NA,
	"elasmobranchii", -439, 0, NA, "rays, skates, and sawfish", NA,
	"elasmosauridae", -130, -66, "elasmosaurus", NA, NA,
	"elasmosaurus", -80.64, -77, NA, NA, NA,
	"elephantidae", -10, 0, "elephas, loxodonta, mammuthus, palaeoloxodon", NA, NA,
	"elephas", -5, 0, NA, "One extant species: E. maximus (Asian elephant).", 'genus',
	"elginerpeton", -375, -375, NA, "'Creeping thing from Elginshire'. Named after Elginshire, Scotland (which became Morayshire in 1919) ", 'genus',
	"enantiornithes", -136, -66, NA, "'opposite birds'.", NA,
	"entelodontidae", -37.2, -15.97, 'daeodon, archaeotherium', NA, NA,
	'daeodon', 29, 15.97, NA, NA, 'genus',
	'archaeotherium', 35, 28, NA, NA, 'genus',
	"eodromaeus", -231.4, -229, NA, "'dawn runner', Argentina", NA,
	"eoraptor", -231, -228, NA, "maybe a sauropodomorph?", NA,
	"eotyrannus", -130, -130, NA, NA, NA,
	"epidexipteryx", -164, -164, NA, NA, NA,
	"equidae*", -57, 0, 'eohippus, orohippus, epihippus, mesohippus, miohippus, parahippus, pliohippus, dinohippus, equus', NA, NA,
	'eohippus', 55.8, 47.8, NA, "'Dawn horse'.", 'genus',
	'orohippus', 54, NA, NA, "'Mountain horse'.", 'genus',
	'epihippus', 46.2, 38.0, NA, NA, 'genus',
	'mesohippus', 37, 32, NA, "'Middle horse'.", 'genus',
	'miohippus', 32, 25, NA, "'Small horse'.", 'genus',
	'parahippus', 24, 17, NA, "'Near horse'.", 'genus',
	'pliohippus', 15.97, 4.9, NA, "More horse.", 'genus',
	'dinohippus', 10.3, 3.6, NA, "'Terrible horse'.", 'genus',
	'equus', 5.33, 0, NA, NA, 'genus',
	"eryops", -299, -273, NA, "'Drawn-out face'. USA. Up to 3 m long - among the largest land animals of their time.", 'genus',
	"erythrosuchus", -249, -244, NA, NA, NA,
	"euarchontoglires*", -67, 0, "lagomorpha, primates, rodentia", NA, NA,
	"eudromaeosauria", -143, -66, "atrociraptor, deinonychus, dromaeosaurus, pyroraptor, utahraptor, velociraptor", NA, NA,
	"euhelopodidae", -145, -88, NA, NA, NA,
	"euoplocephalus", -76.4, -75.6, NA, NA, NA,
	"euornithes", -130.7, 0, "aves, hesperornis, ichthyornis", NA, NA,
	"euparkeria", -247, -247, NA, NA, NA,
	"eureptilia", -311, 0, "araeoscelidia, diapsida", NA, NA,
	"europelta", -113, -113, NA, NA, NA,
	"eutheria", -125, 0, "placentalia", NA, NA,
	"felidae", -30.8, 0, "machairodontinae, panthera", NA, NA,
	'panthera*', 5, 0, NA, NA, NA,
	'machairodontinae*', 14, 0.0117, 'smilodon, homotherium, amphimachairodus', NA, NA,
	'homotherium', 4, 0.012, NA, NA, 'genus',
	'amphimachairodus', 9.8, 5.3, NA, NA, 'genus',
	"fukuiraptor", -125, -115, NA, NA, NA,
	"gallimimus", -70, NA, NA, NA, NA,
	'gastornis*', 60.4, 44.5, NA, 'Europe, North America, Asia.', 'genus',
	'galloanserae*', 68, 0, 'gastornis, dromornithidae', NA, NA,
	'dromornithidae', 25, 0.03, 'dromornis', NA, NA,
	'dromornis', 8, 0.03, NA, "'Swift-running bird'. Australia. Large to enormous flightless birds.", 'genus',
	"gavialidae", -38, 0, "gavialis", NA, NA,
	"gavialis", -20, 0, NA, NA, NA,
	"gavialoidea", -70, 0, "gavialidae", NA, NA,
	"gekkota", -100, 0, NA, NA, NA,
	"giganotosaurus", -99.6, -95, NA, "'giant southern lizard', Argentina", NA,
	"giraffatitan", -150, -145, NA, NA, NA,
	"glyptodon", -3.2, -0.011, NA, NA, NA,
	"glyptodontinae", -38, -0.011, "glyptodon", NA, NA,
	"gnathostomata", -445, 0, "chondrichthyes, osteichthyes, placodermi, acanthodii", "jawed vertbrates", 'infraphylum',
	'acanthodii', 443.8, 252, NA, "'Spiny sharks'.", 'class',
	"gomphotheriidae", -28, -0.01, "gomphotherium", "'Nail beasts'.", NA,
	"gomphotherium", -16, -5, NA, "'Nail beast'. Eurasia, Africa, North America. Double set of straight tusks.", 'genus',
	"gorgonops", -260, -254, NA, "'Gorgon face'.", 'genus',
	"gorgonopsia", -270, -252, "gorgonops, lycaenops, inostrancevia, rubidgea", NA, NA,
	'inostrancevia', 259, 251.9, NA, 'European Russia and Southern Africa. Largest known gorgonopsian.', 'genus',
	'rubidgea', 257, 254, NA, "South Africa and Tanzania.", 'genus',
	"gorgosaurus", -76.5, -75, NA, NA, NA,
	"gracilisuchidae", -247.2, -234, NA, NA, NA,
	"gymnophiona", -223, 0, NA, "'Blind ones'. Caecilians.", 'order',
	"hadrosauridae", -90, -66, "corythosaurus, edmontosaurus, hadrosaurus, lambeosaurus, maiasaura, parasaurolophus, shantungosaurus", NA, NA,
	'ouranosaurus', 121.4, 113.0, NA, 'Africa.', 'genus',
	"hadrosaurus", -83.6, -77.9, NA, NA, NA,
	"herrerasauridae", -233.23, -228.91, "herrerasaurus, staurikosaurus", NA, NA,
	"herrerasaurus", -231.4, -228.91, NA, NA, NA,
	"hesperornis", -83.6, -72, NA, NA, NA,
	"heterodontosaurus", -200, -190, NA, NA, NA,
	"hyaenodontidae", -55.2, -16.9, 'simbakubwa, hyaenodon, megistotherium', NA, NA,
	'simbakubwa', 23.0, 22.0, NA, "'Great lion'. Kenya.", 'genus',
	'hyaenodon', 42.0, 16.9, NA, "'Hyaena tooth'. Eurasia, North America.", 'genus',
	'megistotherium', 19.0, 12.0, NA, NA, 'genus',
	"hypsilophodon", -130, -125, NA, NA, NA,
	"ichthyornis", -95, -83.5, NA, NA, NA,
	"ichthyosauromorpha", -251.3, -90, 'hupehsuchia, shonisaurus, shastasaurus, ophthalmosaurus, ichthyosaurus', NA, NA,
	'hupehsuchia', 248, 247.2, NA, "Name comes from the Hubei Province, China.", 'order',
	'shonisaurus', 227, NA, NA, NA, 'genus',
	'shastasaurus', 235.0, 205.6, NA, "'Mount Shasta lizard'. North America, China.", 'genus',
	'ophthalmosaurus', 165, 157, NA, "'Eye lizard'.", 'genus',
	'ichthyosaurus', 201.4, 184.2, NA, "'Fish lizard'.", 'genus',
	"ichthyostega", -365, -360, NA, "'Fish roof'. Greenland.", 'genus',
	"iguanodon", -126, -122, NA, NA, NA,
	"irritator", -113, -110, NA, NA, NA,
	"kentrosaurus", -152, -152, NA, NA, NA,
	"kimmerosaurus", -152, -150, NA, NA, NA,
	"kronosaurus", -125, -99.6, NA, NA, NA,
	"lagomorpha", -59, 0, NA, NA, NA,
	"lambeosaurus", -76, -75, NA, NA, NA,
	"laurasiatheria*", -85, 0, "artiodactyla, chiroptera, ferae, perissodactyla, uintatherium, mesonychia", NA, NA,
	'ferae', 79.47, 0, 'creodonta, pholidotamorpha, carnivora', NA, NA,
	'pholidotamorpha*', 65, 0, 'palaeanodonta, pholidota', "'Pangolin-like forms'.", NA,
	'palaeanodonta', 62.22, 30.9, NA, "'Ancient toothless'.", NA,
	'pholidota', 47.8, 0, NA, 'Pangolins', NA,
	'creodonta', 63.3, 8.8, 'hyaenodontidae, oxyaenidae', "'Meat teeth'. North America, Europe, Asia, Africa.", NA,
	'oxyaenidae', 58.9, 39.7, NA, NA, NA,
	'mesonychia*', 68, 28.4, 'mesonychidae, hapalodectidae', "'Middle claws'.", NA,
	'mesonychidae*', 67, 28.4, 'mongolestes, ankalagon, dissacus, mesonyx', NA, NA,
	'hapalodectidae*', 55, 33.9, NA, NA, NA,
	'mongolestes', 48.6, 28.4, NA, "'Mongolian robber'. Mongolia.", 'genus',
	'ankalagon', 63.3, 60.2, NA, 'North America. Bear-sized carnivore, named after the dragon Ancalagon in The Silmarillion.', 'genus',
	'dissacus', 66, 50.3, NA, NA, 'genus',
	'mesonyx', 51.8, 51.7, NA, NA, 'genus',
	'uintatherium', 56, 34, NA, 'USA, China', 'genus',
	"lepidosauromorpha", -252, 0, "rhynchocephalia, squamata", NA, NA,
	"lepospondyli", -339, -251.902, "diplocaulus", NA, NA,
	"leptocleididae", -145, -100.5, "leptocleidus", NA, NA,
	"leptocleidus", -135, -125, NA, NA, NA,
	"leptosuchus", -237, -208.5, NA, NA, NA,
	"liopleurodon", -166, -155, NA, NA, NA,
	"lisowicia", -210, -205, NA, NA, NA,
	"lissamphibia", -250, 0, "anura, gymnophiona, urodela", "'Smooth amphibians'. Includes all modern amphibians.", NA,
	"lotosaurus", -238, -238, NA, NA, NA,
	"loxodonta", -7, 0, NA, "Two extant species: L. africana (African bush elephant) and L. cyclotis (African forest elephant).", 'genus',
	"lycaenops", -260, -260, NA, NA, NA,
	"lycopsis", -16.3, -9, NA, NA, NA,
	"lystrosaurus", -255, -248, NA, NA, NA,
	"maiasaura", -86.3, -70.6, NA, NA, NA,
	"mamenchisauridae", -184.5, -114, "mamenchisaurus", NA, NA,
	"mamenchisaurus", -161, -114.4, NA, NA, NA,
	"mammalia", -167, 0, "monotremata, multituberculata, theria", NA, NA,
	"mammaliaformes", -227, 0, "mammalia, morganucodonta", NA, NA,
	"mammaliamorpha", -232, 0, "mammaliaformes", NA, NA,
	"mammut", -8, -0.011, NA, "Aka mastodon ('nipple tooth').", NA,
	"mammuthus", -6.2, -0.004, NA, 'Aka mammuths. Southern and Eastern Africa, Eurasia, North America. incl M. primigenius (the wooly mammuth)', 'genus',
	"mammutidae", -27.5, -0.011, "mammut", "incl mastodons", NA,
	"maniraptora", -167, 0, "alvarezsauridae, oviraptorosauria, paraves, therizinosauridae", NA, NA,
	"mantellisaurus", -130, -120, NA, NA, NA,
	"marginocephalia", -165, -66, "ceratopsia, pachycephalosauria", NA, NA,
	"marsupalia", -66, 0, "diprotodontidae, thylacinidae, thylacoleonidae", NA, NA,
	"massospondylidae", -227, -176, "massospondylus", NA, NA,
	"massospondylus", -200, -183, NA, NA, NA,
	"megalosauridae", -170, -145, "megalosaurus, torvosaurus, eustreptospondylus, afrovenator", NA, NA,
	'afrovenator', 167, 157, NA, "'African hunter'.", 'genus',
	'eustreptospondylus', 166, 154, NA, "'True Streptospondylus' or 'true reversed vertebra'.", 'genus',
	"megalosauroidea", -175, -94, "megalosauridae, spinosauridae", NA, NA,
	"megalosaurus", -166, -165, NA, NA, 'genus',
	"megaraptor", -90, -88, NA, NA, NA,
	"megaraptora", -130, -66, "australovenator, fukuiraptor, megaraptor", NA, NA,
	"megatheriidae", -29, -0.008, "megatherium", NA, NA,
	"megatherium", -5, -0.01, NA, NA, NA,
	"mesosauria", -299, -270.6, NA, NA, NA,
	"metatheria", -125, 0, "marsupalia, sparassodonta, stagodontidae", NA, NA,
	"metoposaurus", -227, -216.5, NA, "'Front lizard'. Europe. Mostly aquatic.", NA,
	"metriacanthosauridae", -174, -125, 'sinraptor', "'Moderately-spined lizards'.", NA,
	'sinraptor', 160, NA, NA, "'Chinese thief'", 'genus',
	"metriorhynchidae", -168, -125, "metriorhynchus, thalattosuchus", NA, NA,
	"metriorhynchus", -157, -150, NA, NA, NA,
	"microraptor", -125, -120, NA, NA, NA,
	"moeritherium", -37, -35, NA, "'The beast from Lake Moeris'. North and West Africa.", 'genus',
	"monotremata", -125, 0, "ornithorhynchidae, tachyglossidae", NA, NA,
	"morganucodonta", -210, -140, NA, NA, NA,
	"mosasauria", -121, -66, "mosasaurus, tylosaurus, prognathodon", NA, NA,
	'prognathodon', 83.6, 66, NA, "'Forejaw tooth'.", 'genus',
	"mosasaurus", -82.7, -66, NA, NA, 'genus',
	"moschops", -265, -260, NA, NA, 'genus',
	"multituberculata", -166, -40, NA, NA, NA,
	"mysticeti", -34, 0, NA, NA, NA,
	"neoaves", -62.5, 0, "phorusrhacidae", NA, NA,
	"neognathae", -72, 0, "galloanserae, neoaves", NA, NA,
	"neovenator", -130, -125, NA, NA, 'genus',
	"noasauridae", -164, -66, NA, NA, NA,
	"nodosauridae", -155, -66, "edmontonia, europelta, nodosaurus, polacanthus, sauropelta, borealopelta", NA, NA,
	"borealopelta", 113.0, 100.5, NA, "'Northern shield'. Canada. Holotype specimen among the best-preserved dinosaur fossils of its size ever found: osteoderms in their life positions + remains of their keratin sheaths, skin, stomach contents, + melanosomes indicating reddish pinkish skin.", 'genus',
	"nodosaurus", -99.7, -86.3, NA, NA, 'genus',
	"nothosauroidea", -251, -210, 'simosaurus, nothosaurus', NA, NA,
	'simosaurus', 240, 230, NA, NA, 'genus',
	'nothosaurus', 240, 210, NA, "'False lizard'", 'genus',
	"notosuchia", -167, -11, "notosuchus, sebecidae, simosuchus", NA, NA,
	"notosuchus", -85, -85, NA, NA, 'genus',
	"odontoceti", -33.9, 0, NA, NA, NA,
	"ophiacodontidae", -308, -273, NA, NA, NA,
	"ornithischia*", -210, -66, "heterodontosaurus, marginocephalia, ornithopoda, thyreophora, kulindadromeus", "'Bird hip'.", NA,
	'kulindadromeus', 168.3, 166.1, NA, "'Kulinda runner'. Russia. Feather-like integument = evidence for protofeathers being basal to Ornithischia (and possibly Dinosauria as a whole, rather than just to Coelurosauria).", 'genus',
	"ornithocheiridae", -140, -90, 'ornithocheirus, tropeognathus', NA, NA,
	'tropeognathus', 112, NA, NA, "'Keel jaw'.", 'genus',
	'ornithocheirus', 105, 93.9, NA, "'bird hand'. UK and poss. Morocco", 'genus',
	"ornithocheiroidea", -145, -66, "anhangueridae, azhdarchidae, ornithocheiridae, pteranodon", NA, NA,
	"ornitholestes", -154, -154, NA, NA, 'genus',
	"ornithomimidae", -96, -66, "gallimimus, ornithomimus, struthiomimus", NA, NA,
	"ornithomimosauria", -140, -66, "deinocheiridae, ornithomimidae", NA, NA,
	"ornithomimus", -76.5, -66, NA, NA, 'genus',
	"ornithopoda", -170, -66, "tenontosaurus, camptosaurus, dryosauridae, hadrosauridae, hypsilophodon, iguanodon, mantellisaurus, ouranosaurus, zalmoxes, muttaburrasaurus, leaellynasaura", NA, NA,
	'leaellynasaura', 118, 110, NA, NA, 'genus',
	'tenontosaurus', 115, 108, NA, "'Sinew lizard'. North America", 'genus',
	'zalmoxes', 70, 66, NA, "Romania. Name after the Dacian deity Zalmoxis.", 'genus',
	'muttaburrasaurus', 112, 103, NA, "Named after Muttaburra, Queensland, Australia.", 'genus',
	"ornithorhynchidae", -26, 0, NA, NA, NA,
	"ornithosuchidae", -228, -203.6, NA, NA, NA,
	"osteichthyes", -430, 0, "actinopterygii, sarcopterygii", "bony fishes", NA,
	"oviraptor", -75, -71, NA, "'Egg thief'. Mongolia.", 'genus',
	'gigantoraptor', 90, NA, NA, "'Giant thief'. Mongolia. Largest-known oviraptorosaur.", 'genus',
	"oviraptorosauria", -130, -66, "oviraptor, gigantoraptor", NA, NA,
	"pachycephalosauria", -100, -66, "pachycephalosaurus", NA, NA,
	"pachycephalosaurus", -70, -66, NA, NA, NA,
	"pachypleurosauria", -251, -227, NA, NA, NA,
	"pachyrhinosaurus", -73.5, -69, NA, NA, NA,
	"pakicetus", -50, -48, NA, NA, NA,
	"palaeognathae", -60, 0, "aepyornithiformes, apterygidae, casuariiformes, dinornithiformes, rheidae, struthionidae", NA, NA,
	"palaeoloxodon", -2.58, -0.0117, NA, 'Africa, Eurasia. Contains the largest known species of elephants.', 'genus',
	"pantestudines", -240, 0, "testudinata", NA, NA,
	"paraceratheriidae", -47, -23, "paraceratherium", NA, NA,
	"paraceratherium", -34, -23, NA, NA, NA,
	"parareptilia", -306, -201.3, "mesosauria, pareiasauria", NA, NA,
	"parasaurolophus", -76.9, -73.5, NA, NA, NA,
	"paraves", -167, 0, "avialae, deinonychosauria, scansoriopterygidae, anchiornithidae", NA, NA,
	"anchiornithidae", 165, 145, "anchiornis, aurornis", NA, NA,
	'anchiornis', 160, NA, NA, NA, 'genus',
	'aurornis', 160, NA, NA, NA, 'genus',
	"pareiasauria", -265, -252, NA, NA, NA,
	"patagotitan", -101.62, -101.62, NA, NA, NA,
	"perissodactyla", -60, 0, "rhinocerotoidea, brontotheriidae, chalicotheriidae, equidae", NA, NA,
	'rhinocerotoidea', 58, 0, 'paraceratheriidae, rhinocerotidae', NA, NA,
	'rhinocerotidae', 40, 0, 'elasmotherium, coelodonta', NA, NA,
	'elasmotherium', 7, 0.039, NA, NA, 'genus',
	'coelodonta', 3.7, 0.014, NA, "'Hollow tooth'. Eurasia. Type species: C. antiquitatis = 'the woolly rhinoceros'", 'genus',
	# 'rhinoceros',
	"phiomia", -37, -30, NA, "North Africa. Relatively small body size. Upper jaw and mandibles both had short tusks.", 'genus',
	"pholidosauridae", -150, -66, "sarcosuchus", NA, NA,
	"phorusrhacidae", -43, -0.1, 'titanis, phorusrhacos, patagornis', "'Terror birds'. South America.", NA,
	'titanis', 5, 1.8, NA, NA, 'genus',
	'phorusrhacos', 20, 13, NA, NA, 'genus',
	'patagornis', 17.5, 11.6, NA, NA, 'genus',
	"phytosauria", -242, -201.4, "leptosuchus, smilosuchus, parasuchus, machaeroprosopus", NA, NA,
	'parasuchus', 222.5, 212, NA, NA, NA,
	'machaeroprosopus', 228, 209, NA, NA, NA,
	"pilosa", -55.8, 0, "megatheriidae", "sloths and anteaters", NA,
	"pistosauroidea", -251, -66, "pistosaurus, plesiosauria", NA, NA,
	"pistosaurus", -247.2, -237, NA, NA, NA,
	"placentalia", -90, 0, "meridiungulata, afrotheria, euarchontoglires, laurasiatheria, xenarthra", NA, NA,
	'meridiungulata*', 65, 0.012, 'litopterna, astrapotheria, notoungulata, xenungulata, pyrotheria', NA, NA,
	'astrapotheria', 59, 6.8, NA, NA, NA,
	'notoungulata', 61, 0.012, 'toxodon', NA, NA,
	'xenungulata', 58.6, 48.7, NA, NA, NA,
	'litopterna', 62.5, 0.012, NA, NA, NA,
	'pyrotheria', 63, 23, NA, NA, NA,
	'toxodon', 5.3, 0.012, NA, NA, NA,
	"placerias", -230, -215, NA, NA, NA,
	"placodermi", -439, -358.9, 'dunkleosteus', "'Plate skin'.", NA,
	'dunkleosteus', 382, 358, NA, NA, 'genus',
	"placodontia", -245, -201.3, NA, NA, NA,
	"plateosaurus", -227, -204, NA, NA, NA,
	"plesiosauria", -232, -66, "cryptoclididae, elasmosauridae, leptocleididae, plesiosaurus, pliosauridae, polycotylidae", NA, NA,
	'polycotylidae', 113, 72, 'plesiopleurodon, polycotylus', 'Known as false pliosaurs.', NA,
	'plesiopleurodon', 98, NA, NA, "'Near to side tooth'.", 'genus',
	'polycotylus', 83.6, NA, NA, "'Much-cupped vertebrae'.", 'genus',
	'plesiosaurus', 199.6, 175.6, NA, "'Near to lizard'. England.", 'genus',
	"pliosauridae", -228, -89.3, "attenborosaurus, kronosaurus, liopleurodon, pliosaurus", NA, NA,
	"pliosaurus", -155.7, -147, NA, "'More lizard'. Includes P. funkei - aka 'Predator X'", NA,
	"polacanthus", -130, -125, NA, NA, NA,
	"poposauridae", -237, -201.3, "poposaurus", "Bipedal carnivores.", NA,
	"poposauroidea", -248, -201.3, "ctenosauriscidae, lotosaurus, poposauridae, shuvosauridae", NA, NA,
	"poposaurus", -237, -216, NA, NA, NA,
	"postosuchus", -237, -201.4, NA, NA, NA,
	"prestosuchidae", -247, -225, "prestosuchus, saurosuchus", NA, NA,
	"prestosuchus", -242, -235, NA, NA, NA,
	"primates", -65.9, 0, 'strepsirrhini, haplorhini', NA, NA,
	'strepsirrhini*', 61, 0, 'adapiformes, lemuriformes', "Aka 'wet-nosed'.", NA,
	'lemuriformes', 40, 0, NA, 'Lemuroids (MAdagascar) and lorisoids (Africa and Asia).', NA,
	'adapiformes', 56.0, 11.1, NA, NA, NA,
	'haplorhini*', 60, 0, 'simiiformes, tarsiiformes', "'Simple-nosed'. Aka 'dry-nosed'.", NA,
	'tarsiiformes*', 58, 0, 'archicebus, tarsiidae', NA, NA,
	'tarsiidae', 45, 0, NA, NA, NA,
	'archicebus', 55.8, 54.8, NA, NA, NA,
	'simiiformes', 40, 0, 'platyrrhini, catarrhini', NA, NA,
	'platyrrhini', 31, 0, NA, "'Flat nosed'. New World monkeys: Central and South America.", NA,
	'catarrhini*', 35, 0, 'hominoidea, cercopithecidae', "'Down nosed'. Old World monkeys.", NA,
	'cercopithecidae*', 30, 0, NA, NA, NA,
	'hominoidea*', 23, 0, 'hominidae, hylobatidae', 'Apes', NA,
	'hylobatidae', 13.8, 0, NA, "Lesser apes i.e. gibbons.", NA,
	'hominidae*', 20, 0, 'ponginae, homininae', "Great apes.", NA,
	'ponginae', 18.5, 0, 'pongo, gigantopithecus', NA, NA,
	'pongo', 2.58, 0, NA, NA, NA,
	'homininae', 12.5, 0, 'hominini, gorillini', NA, NA,
	'gorillini', 8, 0, 'gorilla', NA, NA,
	'hominini', 7, 0, 'homo, pan, australopithecus, ardipithecus', NA, NA,
	'homo', 2.8, 0, NA, NA, 'genus',
	'australopithecus', 4.5, 1.2, NA, NA, 'genus',
	'ardipithecus', 5.77, 4.4, NA, NA, 'genus',
	'pan', 4, 0, NA, NA, 'genus',
	'gorilla*', 4, 0, NA, NA, 'genus',
	'gigantopithecus', 2, 0.3, NA, NA, 'genus',
	"prionosuchus", -299, -272, NA, "Similar in appearance to modern gharial (Gavialis). Holotype total body length estimated to be > 5.5 m, skull estimated to be 50 cm.", 'genus',
	"proboscidea", -60, 0, "phiomia, moeritherium, deinotheriidae, gomphotheriidae, mammutidae, stegodontidae, elephantidae, amebelodontidae", NA, 'order',
	'amebelodontidae', 23, 5.3, 'amebelodon', "Shovel-like mandibular tusks", NA,
	'amebelodon', 9, 5.3, NA, 'North America', 'genus',
	"protoceratops", -75, -71, NA, NA, NA,
	"pseudosuchia", -248, 0, "aetosauria, batrachotomus, crocodylomorpha, gracilisuchidae, ornithosuchidae, phytosauria, poposauroidea, prestosuchidae, rauisuchia, fasolasuchus", NA, NA,
	'fasolasuchus', 220, 213, NA, NA, 'genus',
	"psittacosaurus", -125, -105, NA, NA, NA,
	'pteranodon', 86, 84.5, NA, "Name comes from 'wing' and 'toothless'. North America.", 'genus',
	"pterodactylus", -150.8, -148.5, NA, "'Winged finger'.", 'genus',
	"pterosauria", -228, -66, "dimorphodon, rhamphorhynchidae, pterodactyloidea", NA, NA,
	'pterodactyloidea', 162.7, 66, 'ornithocheiroidea, pterodactylus, tapejaridae', NA, NA,
	'tapejaridae', 125, 85, 'tapejara, tupandactylus', NA, NA,
	'tapejara', 112, NA, NA, NA, 'genus',
	'tupandactylus', 112, NA, NA, NA, 'genus',
	"pyroraptor", -72, -72, NA, NA, NA,
	"rauisuchia", -240, -200, "postosuchus, rauisuchus, polonosuchus", NA, NA,
	'polonosuchus', 237, 227, NA, NA, 'genus',
	"rauisuchus", -235, -228, NA, NA, NA,
	"reptiliomorpha", -340, 0, "amniota, diadectidae, seymouriamorpha", "'Reptile-shaped'.", NA,
	'rhamphorhynchidae', 182, 148.5, 'rhamphorhynchus', NA, NA,
	'rhamphorhynchus', 150.8, 148.5, NA, "'beak snout'.", 'genus',
	"rheidae", -56, 0, NA, NA, NA,
	"rhynchocephalia", -240, 0, NA, NA, NA,
	"rhynchosauria", -251.5, -225, NA, NA, NA,
	"rodentia", -59, 0, 'josephoartigasia', NA, NA,
	'josephoartigasia', 3, 2, NA, 'Uruguay. Biggest rodent ever discovered with a skull length of ~53 cm.', 'genus',
	"rodhocetus", -47, -46, NA, NA, NA,
	"saltasauridae", -85.8, -66, "alamosaurus, saltasaurus", NA, NA,
	"saltasaurus", -70, -68, NA, NA, NA,
	"sarcopterygii", -425, 0, "tetrapodomorpha", "lobe-finned fish", NA,
	"sarcosuchus", -133, -112, NA, NA, NA,
	"sauria", -265.8, 0, "archelosauria, lepidosauromorpha", NA, NA,
	"saurischia*", -237, 0, "sauropodomorpha, theropoda", "'Lizard hip'.", NA,
	"sauropelta", -108.5, -108.5, NA, NA, NA,
	"sauropoda", -228, -66, "brachiosauridae, camarasaurus, cetiosauridae, diplodocidae, euhelopodidae, mamenchisauridae, titanosauria, vulcanodontidae, sauroposeidon", NA, NA,
	'sauroposeidon', 118, 110, NA, "'Lizard earthquake god', after Greek god Poseidon. USA.", 'genus',
	"sauropodomorpha", -235, -66, "massospondylidae, plateosaurus, sauropoda, thecodontosaurus", NA, NA,
	"sauropsida", -311, 0, "eureptilia, parareptilia", NA, NA,
	"sauropterygia", -255, -66, "nothosauroidea, pachypleurosauria, pistosauroidea, placodontia", "'Lizard flippers'.", NA,
	"saurosuchus", -231.4, -225, NA, "'Lizard crocodile'.", NA,
	"scansoriopterygidae", -165, -156, "epidexipteryx, scansoriopteryx", "'climbing wings', China", NA,
	"scansoriopteryx", -165, -156, NA, NA, NA,
	"scelidosaurus", -196.5, -183, NA, NA, NA,
	"sebecidae", -67.6, -11.8, "barinasuchus, sebecus", "the latest surviving group of non-crocodilian crocodylomorphs", NA,
	"sebecus", -59.4, -37.2, NA, NA, NA,
	"serpentes", -94, 0, NA, NA, NA,
	"seymouria", -295, -295, NA, "Named after the town of Seymour, Texas.", 'genus',
	"seymouriamorpha", -305, -295, "seymouria", NA, NA,
	"shantungosaurus", -85, -75, NA, NA, NA,
	"shuvosauridae", -235, -201.3, 'sillosuchus', "Bipedal, lacked sails, had toothless beaks, presumed herbivorous", NA,
	'sillosuchus', 235.0, 221.5, NA, 'South America.', 'genus',
	"simosuchus", -70, -66, NA, NA, NA,
	"sinosauropteryx", -124.6, -122, NA, NA, NA,
	"sirenia", -55.8, 0, NA, NA, NA,
	"smilodon", -2.5, -0.01, NA, NA, 'genus',
	"smilosuchus", -221.5, -205.6, NA, NA, NA,
	"sparassodonta", -66, -2.58, "borhyaenidae, thylacosmilidae", NA, NA,
	"sphenacodon", -300, -280, NA, "'Wedge point tooth'. Low dorsal crest insted of a tall dorsal sail.", 'genus',
	"sphenacodontia", -304, 0, "sphenacodontidae, therapsida", NA, NA,
	"sphenacodontidae", -302, -272, "dimetrodon, sphenacodon", "'Wedge point tooth'.  North America, Europe. Carnivorous 'pelycosaurs'", NA,
	"sphenosuchia", -228, -152, "sphenosuchus", NA, NA,
	"sphenosuchus", -195, -195, NA, NA, NA,
	"spinosauridae", -139, -94, "baryonyx, irritator, spinosaurus", NA, NA,
	"spinosaurus", -100, -94, NA, "'spine lizard', North Africa", NA,
	"squamata", -168, 0, "chamaeleonidae, gekkota, mosasauria, serpentes, varanidae", NA, NA,
	"stagodontidae", -92, -66, "didelphodon", NA, NA,
	"staurikosaurus", -233.23, -228, NA, NA, NA,
	"stegodon", -11.6, -0.01, NA, "'Roofed tooth'. Africa, Asia. Distinctive molar ridges.", 'genus',
	"stegodontidae", -17.3, -0.01, "stegodon", NA, NA,
	"stegosauria", -169, -100.5, "dacentrurus, kentrosaurus, stegosaurus", NA, NA,
	"stegosaurus", -155, -145, NA, NA, 'genus',
	"stokesosaurus", -156.5, -150, NA, NA, 'genus',
	"struthiomimus", -77, -66, NA, NA, 'genus',
	"struthionidae", -21, 0, NA, NA, NA,
	"styracosaurus", -75.5, -74.5, NA, NA, 'genus',
	"synapsida", -318, 0, "caseasauria, edaphosauridae, ophiacodontidae, sphenacodontia, varanopidae", NA, NA,
	# "synapsida", -318, 0, "caseasauria, eupelycosauria", NA, NA,
	'caseasauria', 306, 254, 'caseidae', NA, NA,
	'caseidae', 300, 265, 'cotylorhynchus', NA, NA,
	'cotylorhynchus', 279.5, 270, NA, NA, NA,
	# 'eupelycosauria', 308, 0, "edaphosauridae, ophiacodontidae, varanopidae", NA, NA,
	"tachyglossidae", -5.333, 0, NA, NA, NA,
	"tarbosaurus", -70, -68, NA, NA, 'genus',
	"tawa", -215, -215, NA, NA, 'genus',
	"teleosauridae", -183, -145, "teleosaurus", NA, NA,
	"teleosaurus", -171, -164, NA, NA, 'genus',
	"temnospondyli", -330, -120, "archegosauridae, eryops, lissamphibia, stereospondyli", NA, NA,
	'stereospondyli', 272.95, 120, 'metoposaurus, koolasuchus, siderops', NA, NA,
	'koolasuchus', 125, 120, NA, 'Australia.', 'genus',
	'siderops', 176.6, NA, NA, NA, 'genus',
	"testudinata", -210, 0, 'archelon', NA, NA,
	'archelon', 80.21, 74.21, NA, NA, 'genus',
	"tetanurae", -201, 0, "carnosauria, coelurosauria, megalosauroidea", NA, NA,
	"tetrapoda", -360, 0, "lepospondyli, reptiliomorpha, temnospondyli", "'Four foot'.", 'superclass',
	# "tetrapodomorpha", -409, 0, "eusthenopteron, panderichthys, stegocephalia", NA, NA,
	# "stegocephalia", -380, 0, "tetrapoda, acanthostega, elginerpeton, ichthyostega, tiktaalik", NA, NA,
	"tetrapodomorpha", -409, 0, "eusthenopteron, panderichthys, elginerpeton, tiktaalik, acanthostega, ichthyostega, tetrapoda", NA, NA,
	# 'pederpes', 348, 347.6, NA, NA, NA,
	# "stegocephalia", -380, 0, "tetrapoda, acanthostega, elginerpeton, ichthyostega, tiktaalik", NA, NA,
	"thalattosauria", -247, -201.4, NA, NA, NA,
	"thalattosuchia", -201, -100, "metriorhynchidae, teleosauridae", NA, NA,
	"thalattosuchus", -166, -160, NA, NA, 'genus',
	"thecodontosaurus", -234, -234, NA, NA, 'genus',
	"therapsida", -285, 0, "biarmosuchia, dinocephalia, dicynodontia, gorgonopsia, therocephalia, cynodontia", NA, NA,
	# "therapsida", -285, 0, "dicynodontia, dinocephalia, theriodontia, biarmosuchia", NA, NA,
	# "therapsida", -285, 0, "anomodontia, dinocephalia, theriodontia, biarmosuchia", NA, NA,
	# 'anomodontia', 270, 201, 'dicynodontia', NA, NA,
	'biarmosuchia', 272.5, 252, 'biarmosuchus, eotitanosuchus', NA, NA,
	'biarmosuchus', 267, NA, NA, NA, 'genus',
	'eotitanosuchus', 267, NA, NA, "'Dawn giant crocodile'.", 'genus',
	"theria", -130, 0, "eutheria, metatheria", NA, NA,
	# "theriodontia", -275, 0, "cynodontia, gorgonopsia, therocephalia", NA, NA,
	"therizinosauridae", -100, -66, "therizinosaurus", NA, NA,
	"therizinosaurus", -70, -70, NA, NA, 'genus',
	"therocephalia", -266, -242, 'lycosuchidae, eutherocephalia', "'beast head'.", NA,
	'lycosuchidae', 265, 260, NA, NA, NA,
	'eutherocephalia', 260, 242.5, NA, NA, NA,
	"theropoda", -236, 0, "ceratosauria, coelophysoidea, eodromaeus, eoraptor, herrerasauridae, tawa, tetanurae", NA, NA,
	"thylacinidae", -28, -8e-05, NA, NA, NA,
	"thylacoleonidae", -27, -0.0117, NA, NA, NA,
	"thylacosmilidae", -21, -3, "thylacosmilus", NA, NA,
	"thylacosmilus", -9, -3, NA, NA, 'genus',
	"thyreophora", -200.91, -66, "ankylosauria, scelidosaurus, stegosauria", NA, NA,
	"tiktaalik", -375, -375, NA, "Name means 'large freshwater fish' in Inuktitut. Canada.", 'genus',
	"titanosauria", -140, -66, "argentinosaurus, dreadnoughtus, patagotitan, saltasauridae, paralititan", NA, NA,
	'paralititan', 99.6,93.5, NA, "'Tidal giant'. Egypt. Discovered in coastal deposits.", 'genus',
	"torvosaurus", -165, -148, NA, NA, NA,
	"triceratops", -68, -66, NA, NA, NA,
	"troodon", -77.5, -76.5, NA, "'wounding tooth', USA (Montana)", NA,
	"troodontidae", -150, -66, "troodon", NA, NA,
	"tylosaurus", -92.1, -66, NA, NA, NA,
	"tyrannosauridae", -81.9, -66, "albertosaurus, gorgosaurus, alioramus, daspletosaurus, tarbosaurus, tyrannosaurus", NA, NA,
	"tyrannosauroidea", -166, -66, "dilong, eotyrannus, megaraptora, stokesosaurus, yutyrannus, guanlong, juratyrant, eutyrannosauria", NA, NA,
	'eutyrannosauria*', 90, -66, 'tyrannosauridae, dryptosaurus, appalachiosaurus, bistahieversor', NA, NA,
	'bistahieversor', 75.5, 74.5, NA, NA, 'genus',
	'dryptosaurus', 67, 66, NA, NA, 'genus',
	'appalachiosaurus', 82, 77.9, NA, NA, 'genus',
	'juratyrant', 149, NA, NA, NA, 'genus',
	'guanlong', 160, NA, NA, NA, 'genus',
	"tyrannosaurus", -72.7, -66, NA, NA, NA,
	"tyrannotitan", -113, -100.5, NA, "'tyrant titan', Argentina", NA,
	"urodela", -168, 0, NA, "'Tailed ones'. Newts and salamanders.", 'order',
	"ursidae", -38, 0, NA, NA, NA,
	"utahraptor", -139, -134.6, NA, NA, NA,
	"vancleavea", -228, -201.3, NA, NA, NA,
	"varanidae", -80, 0, 'varanus', NA, NA,
	'varanus*', 20, 0, NA, 'Includes V. komodoensis and V. priscus aka Megalania.', 'genus',
	"varanopidae", -309, -260, NA, "Resembled monitor lizards.", NA,
	"velociraptor", -75, -71, NA, NA, NA,
	"vulcanodontidae", -199, -175, NA, NA, NA,
	"xenarthra", -60, 0, "cingulata, pilosa", NA, NA,
	"yutyrannus", -125, -125, NA, NA, NA,
	'eusthenopteron', 385, NA, NA, "'Good strength fin'.", 'genus',
	'panderichthys', 380, NA, NA, "Named after the German-Baltic paleontologist Christian Heinrich Pander.", 'genus',
	# 'trilobita', 521, 251.9, NA, NA, 'class',
) |>
	dplyr::mutate(to = ifelse(is.na(.data$to), .data$from, .data$to)) |>
	# dplyr::mutate(dplyr::across(c('from', 'to'), ~-abs(.x))) |>
	# # mutate(children = children |> map_chr(function(x) stringr::str_to_lower(str_c(sort(x), collapse=', ')))) |>
	# dplyr::mutate(dplyr::across(c('taxon', 'children'), stringr::str_to_lower)) |>
	# dplyr::select(dplyr::one_of('taxon', 'from', 'to', 'children', 'notes')) |>
	# dplyr::arrange(.data$taxon) |>
	dplyr::mutate(dplyr::across(c('from', 'to'), ~-abs(.x))) |>
	dplyr::mutate(dplyr::across(c('taxon', 'children', 'level'), stringr::str_to_lower)) |>
	dplyr::mutate(asterisk = .data$taxon |> stringr::str_detect('\\*$')) |>
	dplyr::mutate(taxon = .data$taxon |> stringr::str_remove('\\*$')) |>
	dplyr::mutate(children_string=.data$children) |>
	dplyr::mutate(children = .data$children |> tidyr::replace_na('') |> strsplit(split='\\s*,\\s*')) |>
	dplyr::mutate(
		level = dplyr::case_when(
			stringr::str_detect(.data$taxon, 'oidea$') ~ 'superfamily',
			stringr::str_detect(.data$taxon, 'idae$') ~ 'family',
			stringr::str_detect(.data$taxon, 'inae$') ~ 'subfamily',
			stringr::str_detect(.data$taxon, 'ini$') ~ 'tribe',
			stringr::str_detect(.data$taxon, 'inae$') ~ 'subtribe',
			.default=.data$level
		)
	) |>
	identity()

df

# parent
df = dplyr::left_join(
	df,
	df |>
		dplyr::select(parent='taxon', taxon='children') |>
		tidyr::unnest('taxon'),
	by='taxon'
) |>
	dplyr::select(dplyr::one_of('taxon', 'from', 'to', 'parent'),
				  dplyr::starts_with('children'),
				  dplyr::everything())
df

# indicators
df = df |>
	arboretum:::update_indicator_columns() |>
	structure(class = c('tree_data', class(df))) |>
	arboretum:::check_tree_data() |>
	dplyr::arrange(.data$taxon)

df

# labels
# df = update_label_x(df)
# df = df |>
# 	# dplyr::mutate(
# 	# 	label = dplyr::case_when(
# 	# 		.data$level == 'genus' ~ stringr::str_to_sentence(.data$taxon),
# 	# 		.default=.data$taxon
# 	# 	)
# 	# ) |>
# 	dplyr::mutate(
# 		label_x = dplyr::case_when(
# 			.data$is_tip ~ (.data$from + .data$to) / 2,
# 			.default = .data$from
# 		)
# 	)

print(df)

df |>
	dplyr::select(-dplyr::one_of('children_string')) |>
	saveRDS('inst/extdata/tree_data.rds')

df |>
	dplyr::select(-dplyr::one_of('children')) |>
	dplyr::rename(children='children_string') |>
	readr::write_tsv('inst/extdata/tree_data.tsv')


# mbm <- microbenchmark::microbenchmark(
# 	"tsv" = {
# 		df <- readr::read_tsv(
# 			'inst/extdata/tree_data.tsv',
# 			col_types = readr::cols(
# 				from = readr::col_double(),
# 				to = readr::col_double(),
# 				.default = readr::col_character()
# 			)
# 		)
# 	},
# 	"rds" = {
# 		df <- readRDS('inst/extdata/tree_data.rds')
# 	},
# 	times=100
# )
#
# mbm
#
# ggplot2::autoplot(mbm)

# df[df$taxon %in% df$taxon[duplicated(str_remove(df$taxon, '\\*'))], ] |> print()

# children = unlist(map(df$children, str_split, ', '))
# children = discard(unique(children[duplicated(children)]), is.na)
# children
# i = df$children |> map_lgl(function(x) any(str_split(x, ', ') %in% children))
# df[i, ] |> print

# df$level = NA
#
# cat('\n')
# cat('df = tribble(')
# cat('\n')
# cat('~taxon, ~from, ~to, ~children, ~notes, ~level')
# cat('\n')
# for (i in 1:nrow(df)) { # i=1
# 	cat(
# 		paste0('."', df$taxon[i], '."'),
# 		df$from[i],
# 		df$to[i],
# 		df$children_string[i] %>% {ifelse(is.na(.), NA, paste0('."', ., '."'))},
# 		df$notes[i] %>% {ifelse(. == '', NA, paste0('."', ., '."'))},
# 		df$level[i],
# 		sep = ', '
# 	)
# 	cat(', \n')
# }
# cat(')')
# cat('\n')

# source("~/Github/arboretum/scripts/make_tree_data_v2.R") ; devtools::load_all(".") ; tree_app('ichthyosauromorpha')

# source("~/Github/arboretum/scripts/make_tree_data_v2.R") ; devtools::load_all(".") ; tree('ichthyosauromorpha', collapse='none')
