suppressPackageStartupMessages({
	library(magrittr)
	library(tidyverse)
})

tips = tribble(
	~taxon                  , ~from, ~to, ~notes,
	# theropods
	'staurikosaurus'       , 233.23, 228, '',
	'herrerasaurus'        , 231.4 , 228.91, '',
	'eodromaeus'           , 231.4 , 229, "'dawn runner', Argentina",
	'tawa'                 , 215   , NA , '',
	'eoraptor'             , 231   , 228, '', # maybe a sauropodomorph?
	# 'coelophysoidea'       , 227   , 183, '',
	'coelophysis'          , 215   , 208.5, '',
	'dilophosaurus'        , 195.2 , 183.7, "two-crested lizard",
	'ceratosaurus'         , 153   , 148, "'horn lizard', USA",
	'noasauridae'          , 164   ,  66, '',
	# 'abelisauridae'        , 143   ,  66, "'Abel's lizards'",
	'carnotaurus'          ,  72   ,  69, '',
	# 'megalosauridae'       , 170   , 145, "incl. Megalosaurus, Torvosaurus",
	'megalosaurus'         , 166   , 165, '',
	'torvosaurus'          , 165   , 148, '',
	'baryonyx'             , 130   , 125, "'heavy claw', UK",
	'spinosaurus'          , 100   ,  94, "'spine lizard', North Africa",
	'irritator'            , 113   , 110, '',
	'allosaurus'           , 155   , 143.1, '',
	'metriacanthosauridae' , 174   , 125, "'moderately-spined lizards'",
	'tyrannotitan'         , 113   , 100.5, "'tyrant titan', Argentina",
	'neovenator'           , 130   , 125, '',
	'concavenator'         , 125   , NA , '',
	'giganotosaurus'       ,  99.6 ,  95, "'giant southern lizard', Argentina",
	'carcharodontosaurus'  , 100   ,  94, "'jagged toothed lizard', Northwest Africa",
	# 'tyrannosauroidea'     , 166   ,  66,
	# 'tyrannosauridae'      ,  81.9 ,  66, '',
	'yutyrannus'            , 125 , NA, '',
	'stokesosaurus'         , 156.5, 150, '',
	'dilong'                , 130, 122.5, '',
	'eotyrannus'            , 130, NA, '',
	'tyrannosaurus'         , 72.7, 66, '',
	'tarbosaurus'          ,  70  , 68, '',
	'gorgosaurus'          ,  76.5, 75, '',
	'albertosaurus'        ,  71  , 68, '',
	'alioramus'            ,  70  , NA , '',
	'daspletosaurus'       ,  78  , 74.4, '',
	'megaraptor'           ,  90  , 88, '',
	'australovenator'      ,  95  , NA, '',
	'fukuiraptor'          , 125 , 115, '',
	'ornitholestes'        , 154 , 154, '',
	# 'compsognathidae'      , 151.5 , 108, "incl. Compsognathus, Sinosauropteryx",
	'compsognathus'         , 150.8, 145, '',
	'sinosauropteryx'       , 124.6, 122, '',
	# 'ornithomimosauria'    , 140   ,  66,
	# 'ornithomimidae'       ,  96   ,  66, '',
	'struthiomimus'        ,  77   ,  66, '',
	'ornithomimus'         ,  76.5 ,  66, '',
	'gallimimus'           ,  70   ,  NA, '',
	# 'deinocheiridae'       , 115   ,  69, '',
	'deinocheirus'         ,  70   ,  NA, '',
	# 'alvarezsauroidea'     , 160   ,  66, '',
	'alvarezsaurus'        ,  86   ,  83, '',
	# 'therizinosauria'      , 145   ,  66, '',
	'therizinosaurus'      ,  70   ,  NA, '',
	# 'oviraptorosauria'     , 130   ,  66, '',
	'oviraptor'            ,  75   ,  71, '',
	# 'troodontidae'         , 150   ,  66, "'wounding tooth', USA (Montana), incl. Troodon",
	'troodon'              , 77.5  , 76.5, '',
	'deinonychus'          , 115   , 108, '',
	'velociraptor'         ,  75   ,  71, '',
	# 'scansoriopterygidae'  , 165   , 156, "'climbing wings', China, incl. Scansoriopteryx, Epidexipteryx",
	'scansoriopteryx'      , 165  , 156 , '',
	'epidexipteryx'        , 164  , NA , '',
	'microraptor'          , 125   , 120, '',
	'pyroraptor'           ,  72   , NA , '',
	'utahraptor'           , 139   , 134.6, '',
	'atrociraptor'         ,  72.2 ,  71.5, '',
	'dromaeosaurus'        ,  80   ,  69.1, '',
	'archaeopteryx'        , 150.8 , 148.5, "'old-wing', Southern Germany",
	'enantiornithes'       , 136   ,  66, "'opposite birds'",
	'ichthyornis'          ,  95   ,  83.5, '',
	'hesperornis'          ,  83.6 ,  72, '',

	# aves
	'galloanserae'         , 72    ,   0, "maastrichtian",
	'phorusrhacidae'       ,  43   ,   0.1, "terror bids",
	'rheidae'              ,  56   ,   0, '',
	'casuariiformes'       ,  23   ,   0, "cassowarys and emus",
	'apterygidae'          ,  23   ,   0, "kiwis",
	'struthionidae'        ,  21   ,   0, '',
	'dinornithiformes'     ,  17   , 0.0006, "moas, incl Dinornis",
	'aepyornithiformes'    , 2.58  , 0.001, " elephant birds, incl Aepyornis",

	# sauropodomorpha
	# 'massospondylidae'   , 227   , 176, '',
	'massospondylus'     , 200   , 183, '',
	# 'plateosauridae'     , 225   , 190, '',
	'plateosaurus'       , 227   , 204, '',
	'thecodontosaurus'   , 234, NA, '',
	# 'sauropoda'          , 228   ,  66,
	'vulcanodontidae'    , 199   , 175, '',
	# 'mamenchisauridae'   , 184.5 , 114, '',
	'mamenchisaurus'     , 161   , 114.4, '',
	# 'cetiosauridae'      , 178   , 161, '',
	'cetiosaurus'        , 170    , 164.7, '',
	# 'diplodocidae'       , 170   , 136.4, '',
	'barosaurus'         , 152   , 150, '',
	'diplodocus'         , 154   , 152, '',
	'brontosaurus'       , 156.3 , 146.8, '',
	'apatosaurus'        , 152   , 151, '',
	# 'brachiosauridae'    , 160   , 100, '',
	'camarasaurus'     , 155   , 143.1, '',
	'euhelopodidae'      , 145   ,  88, '',
	# 'titanosauria'       , 140   ,  66, '',
	'dreadnoughtus'      ,  76 , 70, '',
	'patagotitan'        , 101.62, NA, '',
	'argentinosaurus'    , 96.2, 92.19, '',
	'alamosaurus'        , 70, 66, '',
	'saltasaurus'        , 70, 68, '',
	'brachiosaurus'      , 154, 150, '',
	'giraffatitan'       , 150, 145, '',

	# 'heterodontosauridae', 201   , 140, '',
	'heterodontosaurus', 200, 190, '',
	'scelidosaurus'      , 196.5 , 183, '',
	# 'stegosauria'        , 169   , 100.5, '',
	'stegosaurus'        , 155     , 145, '',
	'kentrosaurus'       , 152, NA, '',
	'dacentrurus'        , 154  , 140, '',
	# 'nodosauridae'       , 155   ,  66, '',
	'nodosaurus'         , 99.7  , 86.3, '',
	'polacanthus'        , 130   , 125, '',
	'sauropelta'         , 108.5 , NA , '',
	'europelta'          , 113.0 , NA , '',
	'edmontonia'         , 76.5  , 69, '',
	# 'ankylosauridae'     , 122   ,  66, '',
	'ankylosaurus'       , 68    ,  66, '',
	'euoplocephalus'     , 76.4  , 75.6, '',
	# 'ornithopoda'        , 164   ,  66,
	# 'dryosauridae'       , 164   , 115, '',
	'dryosaurus'          , 155, 145, '',
	'hypsilophodon' , 130   , 125, '',
	'iguanodon'     , 126   , 122, '',
	'camptosaurus', 156.3, 146.8, '',
	'mantellisaurus', 130, 120, '',

	# 'hadrosauridae'      ,  86   ,  66, '',
	'hadrosaurus'        ,  83.6 ,  77.9, '',
	'parasaurolophus'    ,  76.9 ,  73.5, '',
	'lambeosaurus'       ,  76   ,  75, '',
	'corythosaurus'      ,  77   ,  75.7, '',
	'maiasaura'          ,  86.3 ,  70.6, '',
	'shantungosaurus'    ,  85   ,  75, '',
	'edmontosaurus'      ,  73   ,  66, '',

	# 'ceratopsia'         , 161   ,  66,
	'psittacosaurus'     , 125   , 105, '',

	# 'ceratopsidae'       ,  82   ,  66, '',
	'chasmosaurus'       , 77 , 76, '',
	'diabloceratops'     , 81.4, 81, '',
	'centrosaurus'       , 76.5, 75.5, '',
	'styracosaurus'      , 75.5, 74.5, '',
	'triceratops'        , 68  , 66, '',
	'pachyrhinosaurus'   , 73.5, 69, '',

	# 'protoceratopsidae'  ,  75   ,  71, '',
	'protoceratops'      ,  75   ,  71, '',

	# 'pachycephalosauria' , 100   ,  66, '',
	'pachycephalosaurus' , 70    , 66, '',

	# pterosauria
	'dimorphodontidae'   , 208   , 182, '',
	'rhamphorhynchidae'  , 182   , 148.5, '',
	'pterodactylus'      , 150.8 , 148.5, "winged finger",
	'ornithocheiridae'   , 140   ,  90, '',
	'anhangueridae'      , 140   ,  92.5, '',
	'azhdarchidae'       ,  92   ,  66, "includes Quetzalcoatlus",
	'pteranodontia'      ,  92   ,  66, '',

	# pseudosuchia
	'ctenosauriscidae'   , 247.5 , 237, "all species had large 'sails' on their backs",
	# 'poposauridae'       , 237   , 201.3, "bipedal carnivores",
	'poposaurus', 237, 216, '',
	'shuvosauridae'      , 235   , 201.3, "theropod-like pseudosuchians",
	# 'prestosuchidae'     , 247   , 225, '',
	'prestosuchus', 242, 235, '',
	'batrachotomus', 242, 237, '',
	'gracilisuchidae', 247.2, 234, '',
	# 'phytosauria'        , 242   , 201.4, '',
	'smilosuchus', 221.5, 205.6, '',
	'leptosuchus', 237, 208.5, '',
	# 'rauisuchia'         , 240   , 200, '',
	'postosuchus*', 237, 201.4, '',
	'rauisuchus', 235, 228, '',
	'lotosaurus', 238.0, NA, '',

	# 'aetosauria'         , 231.4 , 201.4, '',
	'desmatosuchus', 228, 210, '',
	'aetosaurus*', 227.3, 205.7, '',
	'saurosuchus'        , 231.4 , 225, '',
	'ornithosuchidae'    , 228   , 203.6, '',
	# 'sphenosuchia'       , 228   , 152, '',
	'sphenosuchus', 195, NA, '',
	# 'thalattosuchia'     , 201   , 100,
	# 'teleosauridae'      , 183   , 145, '',
	'teleosaurus', 171, 164, '',
	# 'metriorhynchidae'   , 168   , 125, '',
	'metriorhynchus', 157, 150, '',
	'thalattosuchus', 166, 160, '',
	'sarcosuchus'        , 133   , 112, '',
	# 'sebecidae'          ,  67.6 , 11.8, "the latest surviving group of non-crocodilian crocodylomorphs",
	'sebecus', 59.4, 37.2, '',
	'barinasuchus', 42.2, 11.8, '',
	'notosuchus', 85, NA, '',
	'simosuchus', 70, 66, '',
	# 'alligatoroidea*'    ,  78   ,   0, "campanian",
	'deinosuchus', 82, 73, '',
	'alligator', 37.2, 0, '',
	'caiman', 16, 0, '',
	'gavialis', 20, 0, '',
	# 'crocodyloidea*'     ,  70   ,   0, "maastrichtian",
	'crocodylus', 25, 0, '',
	# 'gavialoidea*'       ,  70   ,   0, "maastrichtian",
		# 'gavialidae', 38, 0, '',
	'rhynchosauria'      , 251.5 , 225, '',
	'euparkeria', 247, NA, '',
	'vancleavea', 228, 201.3, '',
	'erythrosuchus', 249, 244, '',
	'ichthyosauromorpha' , 251.3 ,  90, '',
	'nothosauroidea'     , 251   , 210, '',
	'pachypleurosauria'  , 251   , 227, '',
	'placodontia'        , 245   , 201.3, '',
	'pistosaurus'        , 247.2 , 237, '',

	'cryptoclidus', 166, 160, '',
	'kimmerosaurus', 152, 150, '',

	# 'pliosauridae'       , 228   ,  89.3, '',
	'kronosaurus', 125, 99.6, '',
	'pliosaurus', 155.7, 147, '',
	'liopleurodon', 166, 155, '',
	'attenborosaurus', 196.5, 189.6, '',
	'plesiosauridae'     , 199.6 , 174.7, '',
	# 'leptocleididae'     , 145   , 100.5, '',
	'leptocleidus', 135, 125, '',
	# 'elasmosauridae'     , 130   ,  66, '',
	'elasmosaurus', 80.64, 77, '',
	'thalattosauria'     , 247   , 201.4, '',
	'araeoscelidia'      , 302   , 275.6, '',
	'testudinata'        , 210   ,   0, '',
	'rhynchocephalia'    , 240   ,   0, '',
	# 'mosasauria'         , 121   ,  66, '',
	'tylosaurus', 92.1, 66, '',
	'mosasaurus', 82.7, 66, '',
	'gekkota'            , 100   ,   0, '',
	'varanidae'          ,  80   ,   0, '',
	'chamaeleonidae'     ,  26   ,   0, '',
	'serpentes'             ,  94   ,   0, '',
	'mesosauria'         , 299   , 270.6, '',
	'pareiasauria'       , 265   , 252, '',

	# synapsids
	'ophiacodontidae'    , 308   , 273, '',
	# 'edaphosauridae'     , 307   , 272, '',
	'edaphosaurus'       , 303.4 , 272.5, '',
	# 'diadectidae'        , 305   , 256, "incl. diadectes = 'crosswise-biter' one of the first herbivorous tetrapods, one of the first fully terrestrial vertebrates to attain large size",
	'diadectes'          , 290   , 272, '',
	'diasparactus'       , 296.4, 295.0, '',

	# 'sphenacodontidae'   , 300   , 272, "'wedge point tooth family' includes Dimetrodon",
	'dimetrodon'         , 295   , 270, '',
	'sphenacodon'        , 300   , 280, '',
	# 'dinocephalia'       , 279   , 260, "'terrible head'
	'moschops'           , 265   , 260, '',
	'biarmosuchia'       , 272.5 , 252, '',
	# 'gorgonopsia'        , 270   , 252, '',
	'gorgonops'          , 260   , 254, '',
	'lycaenops'          , 260, NA, '',

	# 'dicynodontia'       , 268   , 201.4, "'two dog tooth' includes Lystrosaurus",
	'lisowicia'          , 210   , 205, '',
	'lystrosaurus'       , 255   , 248, '',
	'placerias'          , 230   , 215, '',

	'cynognathus', 247, 237, '',

	'varanopidae'        , 309, 260, '',

	'therocephalia'      , 266   , 242, "'beast head'",
	'morganucodonta'     , 210   , 140, '',
	'multituberculata'   , 166   ,  40, '',
	'didelphodon', 73, 66, '',
	# 'monotremata'        , 125   ,   0, '',
	'ornithorhynchidae', 26, 0, '',
	'tachyglossidae*' , 5.333, 0, '',
	# 'marsupalia'         ,  66   ,   0, '',
	# 'diprotodontia', 28, 0, '',
	# 'diprotodontidae', 28.4, 0.04, 'giant wombats',
	'diprotodon', 1.77, 0.04, '',
	'thylacoleonidae*', 27, 0.0117, '',
	'thylacinidae', 28, 0.00008, '',
	# 'proboscidea'        ,  60   ,   0, '',
	# 'deinotheriidae'      , 28 , 1, '',
	'deinotherium*'        , 13 , 1, '',
	'gomphotherium'        , 16 , 5 , '',
	'stegodon'         , 11.6, 0.01, '',
	'mammuthus'         , 6.2, 0.004, '',
	'palaeoloxodon'     , 2.58, 0.0117, '',
	'loxodonta'         , 7, 0,  'African elephants',
	'elephas'         , 5, 0,  'Asian elephants',
	'moeritherium',  37, 35, '',

	'sirenia'            ,  55.8 ,   0, '',
	# 'cingulata'          ,  58.7 ,   0, "armadillos including Glyptodont",
	'glyptodon'          , 3.200 , 0.011, '',
	# 'pilosa'             ,  55.8 ,   0, "sloths and anteaters",
	'megatherium'         , 5 , 0.010, '',
	'smilodon'           , 2.5 , 0.01, '',
	'ursidae'            , 38   , 0, '',
	'canidae'            , 37.8, 0, '',
	'chiroptera'         ,  56   ,   0, '',
	'hyaenodontidae'     ,  55.2 ,  16.9, '',
	# 'perissodactyla'     ,  56   ,   0, "Tapiridae, Brontotheriidae, Equidae, Chalicotheriidae, Rhinocerotidae, Paraceratheriidae",
	'paraceratherium', 34, 23, '',
	'chalicotheriidae'  , 48.6, 1.806, '',
	'equidae'           , 55.8, 0, '',
	'brontotheriidae', 56, 34, '',

	'basilosaurus'     ,  41.3 , 33.9, '',
	'dorudon', 41.03, 33.9, '',
	'rodhocetus', 47, 46, '',
	'ambulocetus', 48, 47, '',
	'pakicetus', 50, 48, '',

	'mysticeti'          ,  34   ,   0, '',
	'odontoceti'         ,  33.9 ,   0, '',
	'andrewsarchus'      ,  47.8 ,  37.71, '',
	'entelodontidae'     ,  37.2 ,  15.97, '',
	'lagomorpha'         ,  59   ,   0, '',
	'rodentia'           ,  59   ,   0, '',
	'primates'           ,  65.9 ,   0, '',
	'thylacosmilus'      , 9, 3, '',
	'borhyaena', 21.0, 15.5, '',
	'lycopsis', 16.3, 9.0, '',

	'seymouriamorpha'    , 305 , 295, '',

	# 'sauria', 268.5, 0,
	# 'chalicotherioidea', 48.6  , 0.005,
	# 'equidae', 55.8, 0,
	# 'phorusrhacidae', 43, 0.1,

	# 'lepospondyli'     , 339   , 251.902, '',
	'eryops'           , 299   , 273, '',
	# 'archegosauridae*' , 300   , 252, "includes Prionosuchus",
	'prionosuchus', 299, 272, '',
	'archegosaurus', 299, 253, '',
	'gymnophiona'      , 223   ,   0, "caecilian",
	'anura'            , 200   ,   0, "frogs and toads",
	'urodela'          , 168   ,   0, "salamanders",
	'diplocaulus'      , 306   , 255, '',
	'tiktaalik'        , 375   , NA, '',
	'elginerpeton'     , 375   , NA, '',
	'ichthyostega'     , 365   , 360, '',
	'acanthostega'     , 365   , NA, '',
	'metoposaurus'     , 227   , 216.5, '',
	# 'Ichthyostegalia'  , 368   , 329,
) %>%
	dplyr::mutate(to = ifelse(is.na(to), from, to))

tips

relations = tribble(
	~taxon             , ~from , ~to, ~children,

	'aves*'            ,  75   , NA , c('neognathae', 'palaeognathae'),
	'neognathae'       ,  72   , NA , c('galloanserae', 'neoaves'),
	'neoaves'          , 62.5  , NA , c('phorusrhacidae'),
	'palaeognathae'    ,  60   , NA , c('rheidae', 'casuariiformes', 'apterygidae', 'struthionidae', 'dinornithiformes', 'aepyornithiformes'),

	'afrotheria'       ,  65   , NA , c('proboscidea', 'sirenia'),
	'proboscidea'      ,  60   ,  0 , c('deinotheriidae', 'gomphotheriidae', 'elephantidae', 'stegodon', 'moeritherium'),
	'gomphotheriidae'  , 28 , 0.01, c('gomphotherium'),
	'deinotheriidae'      , 28 , 1, c('deinotherium'),
	'elephantidae'     , 10 , 0, c('mammuthus', 'palaeoloxodon', 'loxodonta', 'elephas'),
	'amniota'          , 323   , NA , c('sauropsida', 'synapsida'),
	'ankylosauria'     , 167   , NA , c('nodosauridae', 'ankylosauridae'),
	'nodosauridae'     , 155   , NA , c('nodosaurus', 'polacanthus', 'sauropelta', 'europelta', 'edmontonia'),
	'ankylosauridae'   , 122   , NA , c('ankylosaurus', 'euoplocephalus'),
	# 'anomodontia'      , 270   , NA , c('dicynodontia'),
	'dicynodontia'     , 268   , 201.4, c('lisowicia', 'lystrosaurus', 'placerias'),
	'archelosauria'    , 260   , NA , c('archosauromorpha', 'pantestudines'),
	'artiodactyla*'     , 60    , NA , c('cetacea', 'andrewsarchus', 'entelodontidae'),
	'archosauria'      , 248   , NA , c('avemetatarsalia', 'pseudosuchia'),
	'archosauromorpha' , 260   , NA , c('rhynchosauria', 'archosauriformes', 'ichthyosauromorpha', 'sauropterygia', 'thalattosauria'),
	'archosauriformes' , 252, 0, c('archosauria', 'vancleavea', 'euparkeria', 'erythrosuchus'),
	# 'avemetatarsalia'  , 247   , NA , c('dinosauromorpha', 'pterosauria'),
	'avemetatarsalia'  , 247   , NA , c('dinosauria', 'pterosauria'),
	'cetacea'          ,  56   , NA , c('basilosauridae', 'odontoceti', 'mysticeti', 'rodhocetus', 'ambulocetus', 'pakicetus'),
	'basilosauridae', 43, 33.9, c('basilosaurus', 'dorudon'),
	'crocodylomorpha'  , 235   , NA , c('sphenosuchia', 'crocodyliformes', 'thalattosuchia'),
	'sphenosuchia'       , 228   , 152, c('sphenosuchus'),
	'crocodyliformes'  , 225   , NA , c('crocodilia', 'pholidosauridae', 'notosuchia'),
	'pholidosauridae', 150, 66, c('sarcosuchus'),
	'notosuchia', 167, 11, c('sebecidae', 'notosuchus', 'simosuchus'),
	'sebecidae', 67.6 , 11.8, c('sebecus', 'barinasuchus'),
	'crocodilia'       , 100   , NA , c('alligatoroidea', 'crocodyloidea', 'gavialoidea'),
	'gavialoidea*'       ,  70   ,   0, c('gavialidae'),
	'gavialidae', 38, 0, c('gavialis'),
	'crocodyloidea*'     ,  70   ,   0, c('crocodylidae'),
	'crocodylidae', 46, 0, c('crocodylus'),
	'alligatoroidea*'  ,  90   ,   0, c('deinosuchus', 'alligator', 'caiman'),
	'cynodontia'       , 260   , NA , c('mammaliamorpha', 'cynognathus'),
	'mammaliamorpha'   , 232   , NA , c('mammaliaformes'),
	'mammaliaformes'   , 227   , NA , c('mammalia', 'morganucodonta'),
	# 'dinosauromorpha'  , 247   , NA , c('dinosauria'),
	'dinosauria*'      , 240   , NA , c('saurischia', 'ornithischia'),
	'euarchontoglires' ,  66   , NA , c('lagomorpha', 'rodentia', 'primates'),
	'eureptilia'       , 311   , NA , c('diapsida', 'araeoscelidia'),
	'diapsida'         , 302   , NA , c('sauria'),
	'eutheria'        , 125   , NA , c('placentalia'),
	'laurasiatheria'   ,  65   , NA , c('chiroptera', 'carnivora', 'perissodactyla', 'artiodactyla', 'hyaenodontidae'),
	'perissodactyla*'     ,  60   ,   0, c('paraceratheriidae', 'chalicotheriidae', 'equidae', 'brontotheriidae'),
	'paraceratheriidae', 47, 23, c('paraceratherium'),
	'carnivora'        , 51.88,   0, c('felidae', 'canidae', 'ursidae'),
	'felidae'            , 30.8 , 0 , c('smilodon'),
	'lepidosauromorpha', 252   , NA , c('squamata', 'rhynchocephalia'),
	'mammalia'         , 167   , NA , c('theria', 'monotremata', 'multituberculata'),
	'monotremata'        , 125   ,   0, c('ornithorhynchidae', 'tachyglossidae'),
	'stagodontidae', 92, 66, c('didelphodon'),
	'marginocephalia*' , 165   , NA , c('ceratopsia', 'pachycephalosauria'),
	'pachycephalosauria' , 100, 66, c('pachycephalosaurus'),
	'ceratopsia'       , 161   , NA , c('psittacosaurus', 'ceratopsidae', 'protoceratops'),
	'ceratopsidae*'       ,  90   ,  66, c('chasmosaurus', 'diabloceratops', 'centrosaurus', 'styracosaurus', 'triceratops', 'pachyrhinosaurus'),
	'metatheria'      , 125   , NA , c('marsupalia', 'sparassodonta', 'stagodontidae'),
	'marsupalia'         ,  66   ,   0, c('diprotodontidae', 'thylacoleonidae', 'thylacinidae'),
	'diprotodontidae', 28.4, 0.04, c('diprotodon'),
	'sparassodonta', 66, 2.58, c('borhyaenidae', 'thylacosmilidae'),
	'thylacosmilidae' , 21, 3, c('thylacosmilus'),
	'borhyaenidae*', 63.0, 5.333, c('borhyaena', 'lycopsis'),

	# 'ornithischia*'    , 235   , NA , c('thyreophora', 'heterodontosauridae', 'ornithopoda', 'marginocephalia'),
	# 'heterodontosauridae', 201   , 140, c('heterodontosaurus'),
	'ornithischia*'    , 235   , NA , c('thyreophora', 'heterodontosaurus', 'ornithopoda', 'marginocephalia'),
	'thyreophora'      , 201   , NA , c('scelidosaurus', 'ankylosauria', 'stegosauria'),
	'stegosauria'      , 169   , 100.5, c('stegosaurus', 'kentrosaurus', 'dacentrurus'),
	'ornithocheiroidea', 145   , NA , c('ornithocheiridae', 'azhdarchidae', 'pteranodontia', 'anhangueridae'),
	'ornithopoda*'     , 170   , NA , c('dryosauridae', 'hypsilophodon', 'iguanodon', 'hadrosauridae', 'camptosaurus', 'mantellisaurus'),
	'dryosauridae'     , 164   , 115, c('dryosaurus'),
	'hadrosauridae*'   ,  90   , 66, c('hadrosaurus', 'parasaurolophus', 'lambeosaurus', 'corythosaurus', 'maiasaura', 'shantungosaurus', 'edmontosaurus'),
	'pantestudines'    , 240   , NA , c('testudinata'),
	'placentalia*'     ,  90   , NA , c('xenarthra', 'afrotheria', 'laurasiatheria', 'euarchontoglires'),
	'parareptilia'     , 306   , NA , c('pareiasauria', 'mesosauria'),
	'poposauroidea'    , 248   , NA , c('poposauridae', 'shuvosauridae', 'ctenosauriscidae', 'lotosaurus'),
	'poposauridae'       , 237   , 201.3, c('poposaurus'),
	'pistosauroidea'   , 251   , NA , c('pistosaurus', 'plesiosauria'),
	'plesiosauria*'    , 232   , NA , c('pliosauridae', 'plesiosauridae', 'elasmosauridae', 'leptocleididae', 'cryptoclididae'),
	'elasmosauridae'     , 130   ,  66, 'elasmosaurus',
	'leptocleididae'     , 145   , 100.5, c('leptocleidus'),
	'cryptoclididae', 170, 130, c('cryptoclidus', 'kimmerosaurus'),
	'pliosauridae'       , 228   ,  89.3, c('kronosaurus', 'pliosaurus', 'liopleurodon', 'attenborosaurus'),
	'pseudosuchia'     , 248   , NA , c('prestosuchidae', 'poposauroidea', 'ornithosuchidae', 'phytosauria', 'aetosauria', 'rauisuchia', 'crocodylomorpha', 'gracilisuchidae', 'batrachotomus'),
	'phytosauria'        , 242   , 201.4, c('smilosuchus', 'leptosuchus'),
	'aetosauria'         , 231.4 , 201.4, c('desmatosuchus', 'aetosaurus'),
	'rauisuchia'         , 240   , 200, c('postosuchus', 'rauisuchus'),
	'prestosuchidae'     , 247   , 225, c('prestosuchus', 'saurosuchus'),
	'pterosauria'      , 228   , NA , c('pterodactyloidea', 'dimorphodontidae', 'rhamphorhynchidae'),
	'pterodactyloidea' , 162.7 , NA , c('pterodactylus', 'ornithocheiroidea'),
	'sauria'           , 265.8 , NA , c('lepidosauromorpha', 'archelosauria'),
	'saurischia*'      , 237   , NA , c('sauropodomorpha', 'theropoda'),
	# 'sauropodomorpha'  , 230   , NA , c('massospondylidae', 'plateosauridae', 'sauropoda'),
	'sauropodomorpha*'  , 234   , NA , c('massospondylidae', 'plateosaurus', 'sauropoda', 'thecodontosaurus'),
	'massospondylidae' , 227   , NA , c('massospondylus'),
	# 'plateosauridae'   , 225   , NA , c('plateosaurus'),
	'sauropoda'        , 201   , NA , c('vulcanodontidae', 'mamenchisauridae', 'cetiosauridae', 'diplodocidae', 'brachiosauridae', 'camarasaurus', 'euhelopodidae', 'titanosauria'),
	'cetiosauridae'    , 178   , NA , c('cetiosaurus'),
	'mamenchisauridae' , 184.5 , NA , c('mamenchisaurus'),
	'diplodocidae'     , 170   , NA , c('barosaurus', 'diplodocus', 'brontosaurus', 'apatosaurus'),
	'brachiosauridae'  , 160   , NA , c('brachiosaurus', 'giraffatitan'),
	'titanosauria'     , 140   , NA , c('dreadnoughtus', 'patagotitan', 'argentinosaurus', 'saltasauridae'),
	'saltasauridae'    , 85.8  , 66 , c('alamosaurus', 'saltasaurus'),

	'sauropsida'       , 311   , NA , c('parareptilia', 'eureptilia'),
	'sauropterygia*'   , 255   , NA , c('nothosauroidea', 'pachypleurosauria', 'placodontia', 'pistosauroidea'),
	'sphenacodontia'   , 304   , NA , c('sphenacodontidae', 'therapsida'),
	'sphenacodontidae*', 302   , 272, c('dimetrodon', 'sphenacodon'),
	'squamata'         , 168   , NA , c('serpentes', 'mosasauria', 'varanidae', 'gekkota', 'chamaeleonidae'),
	'mosasauria'       , 121   ,  66, c('tylosaurus', 'mosasaurus'),

	# 'synapsida'        , 318   , NA , c('edaphosauridae', 'diadectidae', 'ophiacodontidae', 'sphenacodontia', 'varanopidae'),
	'synapsida'        , 318   , NA , c('edaphosauridae', 'ophiacodontidae', 'sphenacodontia', 'varanopidae'),
	'diadectidae'      , 305   , 256, c('diadectes', 'diasparactus'),
	'edaphosauridae'     , 307   , 272, c('edaphosaurus'),

	# theropods
	'theropoda*'       , 236   , NA , c('herrerasauridae', 'eodromaeus', 'tawa', 'eoraptor', 'coelophysoidea', 'ceratosauria', 'tetanurae'),
	'coelophysoidea'   , 227   , 183, c('dilophosaurus', 'coelophysis'),
	'herrerasauridae'  , 233.23, NA , c('herrerasaurus', 'staurikosaurus'),
	'megalosauroidea*' , 175   , NA , c('spinosauridae', 'megalosauridae'),
	'megalosauridae'   , 170   , 145, c('megalosaurus', 'torvosaurus'),
	'spinosauridae'    , 139   , NA , c('spinosaurus', 'baryonyx', 'irritator'),
	'ceratosauria'     , 199.3 , NA , c('ceratosaurus', 'noasauridae', 'abelisauridae'),
	'abelisauridae'    , 143   , 66 , c('carnotaurus'),
	'tetanurae*'       , 201   , NA , c('megalosauroidea', 'carnosauria', 'coelurosauria'),
	'tetrapoda'        , 370   , NA , c('temnospondyli', 'lepospondyli', 'reptiliomorpha'),
	# 'seymouriamorpha'  , 305   , c('seymouria'),
	'reptiliomorpha'   , 340   , NA , c('amniota', 'seymouriamorpha', 'diadectidae'),
	'carnosauria*'     , 180   , NA , c('allosauridae', 'metriacanthosauridae', 'carcharodontosauridae'),
	'allosauridae'     , 179.17, NA , c('allosaurus'),
	'carcharodontosauridae',154, NA , c('carcharodontosaurus', 'giganotosaurus', 'tyrannotitan', 'neovenator', 'concavenator'),
	'paraves*'         , 167   , NA , c('scansoriopterygidae', 'deinonychosauria', 'avialae'),
	'scansoriopterygidae', 165 ,156 , c('scansoriopteryx', 'epidexipteryx'),
	'deinonychosauria' , 167   , NA , c('dromaeosauridae', 'troodontidae'),
	'troodontidae'     , 150   , 66 , c('troodon'),
	'maniraptora*'     , 167   , NA , c('alvarezsauridae', 'therizinosauridae', 'oviraptoridae', 'paraves'),
	'therizinosauridae*', 100, 66, c('therizinosaurus'),
	'alvarezsauridae'  ,  97   , 66 , c('alvarezsaurus'),
	'oviraptoridae'    ,  84   , 66,  c('oviraptor'),
	# 'oviraptorosauria' , 130   , 66 , c('oviraptor'),
	# 'therizinosauria'  , 145   , 66 , c('therizinosaurus'),
	'avialae'          , 150.8 , NA , c('archaeopteryx', 'enantiornithes', 'euornithes'),
	'euornithes'       , 130.7 , NA , c('aves', 'ichthyornis', 'hesperornis'),
	'coelurosauria*'   , 170   , NA , c('ornitholestes', 'tyrannosauroidea', 'maniraptora', 'compsognathidae', 'ornithomimosauria'),
	'compsognathidae'  , 151.5 , 108, c('compsognathus', 'sinosauropteryx'),
	'ornithomimosauria', 140   , NA , c('ornithomimidae', 'deinocheiridae'),
	'deinocheiridae'   , 115   , 69 , c('deinocheirus'),
	'ornithomimidae'   ,  96   , 66 , c('struthiomimus', 'ornithomimus', 'gallimimus'),
	'dromaeosauridae'  , 145   , NA , c('eudromaeosauria', 'microraptor'),
	'eudromaeosauria'  , 143   , 66 , c('deinonychus', 'velociraptor', 'pyroraptor', 'utahraptor', 'atrociraptor', 'dromaeosaurus'),
	'tyrannosauroidea' , 166   , NA , c('tyrannosauridae', 'yutyrannus', 'stokesosaurus', 'dilong', 'eotyrannus', 'megaraptora'),
	'megaraptora'      , 130   , 66 , c('megaraptor', 'australovenator', 'fukuiraptor'),
	'tyrannosauridae'  ,  81.9 , 66 , c('tyrannosaurus', 'tarbosaurus', 'gorgosaurus', 'albertosaurus', 'alioramus', 'daspletosaurus'),
	'thalattosuchia'   , 201   , NA , c('teleosauridae', 'metriorhynchidae'),
	'metriorhynchidae'   , 168   , 125, c('metriorhynchus', 'thalattosuchus'),
	'teleosauridae'      , 183   , 145, c('teleosaurus'),
	# 'therapsida*'      , 285   , NA , c('anomodontia', 'dinocephalia', 'theriodontia'),
	# 'therapsida*'      , 285   , NA , c('dicynodontia', 'dinocephalia', 'theriodontia'),
	'therapsida*'      , 285   , NA , c('dicynodontia', 'dinocephalia', 'gorgonopsia', 'therocephalia', 'cynodontia', 'biarmosuchia'),
	# 'theriodontia*'    , 275   , NA , c('gorgonopsia', 'therocephalia', 'cynodontia'),
	'gorgonopsia'      , 270   , 252, c('gorgonops', 'lycaenops'),
	'dinocephalia'     , 279   , NA , c('moschops'),
	# 'theria*'           , 125   , NA , c('placentalia', 'marsupalia'),
	'theria*'          , 130   , NA , c('metatheria', 'eutheria'),
	'xenarthra'        ,  60   , NA , c('cingulata', 'pilosa'),
	'cingulata'          ,  58.7 ,   0, c('glyptodontinae'),
	'glyptodontinae'     , 38 , 0.011 , c('glyptodon'),

	'pilosa'             ,  55.8 ,   0, c('megatheriidae'),
	'megatheriidae'     , 29, 0.008, c('megatherium'),

	'tetrapodomorpha'  , 409   , NA , c('tetrapoda', 'stegocephalia'),
	'stegocephalia'    , 375   , NA , c('tiktaalik', 'elginerpeton', 'ichthyostega', 'acanthostega'),
	'temnospondyli'    , 330   , NA , c('eryops', 'archegosauridae', 'lissamphibia', 'metoposaurus'),
	'archegosauridae*' , 300   , 252, c('prionosuchus', 'archegosaurus'),
	'lissamphibia'     , 250   , NA , c('anura', 'urodela', 'gymnophiona'),
	'lepospondyli'     , 339   , NA , c('diplocaulus'),
)

relations

dplyr::bind_rows(tips, relations) %>%
	dplyr::mutate(across(c(from, to), ~-abs(.x))) %>%
	dplyr::mutate(children = children %>% map_chr(function(x) str_to_lower(str_c(x, collapse=',')))) %>%
	dplyr::mutate(across(c(taxon, children), str_to_lower)) %>%
	dplyr::select(taxon, from, to, children, notes) %>%
	write_tsv('inst/extdata/tree_data.tsv')





